project_name: med

version: 2

before:
  hooks:
    - go mod download
    - go mod tidy
    - apt-get update && apt-get install -y libmvec-dev musl-dev=1.2.2-1

env:
  - CGO_ENABLED=1

builds:
  - id: "med-darwin-amd64"
    main: ./cmd/med/main.go
    binary: med
    hooks:
      pre:
        - wget https://github.com/CosmWasm/wasmvm/releases/download/{{ .Env.COSMWASM_VERSION }}/libwasmvmstatic_darwin.a -O /lib/libwasmvmstatic_darwin.a
    env:
      - CC=o64-clang
      - CXX=o64-clang++
      - CGO_LDFLAGS=-L/lib -mmacosx-version-min=10.12
      - CGO_CFLAGS=-mmacosx-version-min=10.12
    goos:
      - darwin
    goarch:
      - amd64
    flags:
      - -mod=readonly
      - -trimpath
    ldflags:
      - -X github.com/cosmos/cosmos-sdk/version.Name=me-hub
      - -X github.com/cosmos/cosmos-sdk/version.AppName=med
      - -X github.com/cosmos/cosmos-sdk/version.Version={{.Version}}
      - -X github.com/cosmos/cosmos-sdk/version.Commit={{.Commit}}
      - -X github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,ledger,static_wasm
      - -s -w
      - -linkmode=external
    tags:
      - netgo
      - ledger
      - static_wasm

  - id: "med-darwin-arm64"
    main: ./cmd/med/main.go
    binary: med
    hooks:
      pre:
        - wget https://github.com/CosmWasm/wasmvm/releases/download/{{ .Env.COSMWASM_VERSION }}/libwasmvmstatic_darwin.a -O /lib/libwasmvmstatic_darwin.a
    env:
      - CC=oa64-clang
      - CXX=oa64-clang++
      - CGO_LDFLAGS=-L/lib
    goos:
      - darwin
    goarch:
      - arm64
    flags:
      - -mod=readonly
      - -trimpath
    ldflags:
      - -X github.com/cosmos/cosmos-sdk/version.Name=me-hub
      - -X github.com/cosmos/cosmos-sdk/version.AppName=med
      - -X github.com/cosmos/cosmos-sdk/version.Version={{.Version}}
      - -X github.com/cosmos/cosmos-sdk/version.Commit={{.Commit}}
      - -X github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,ledger,static_wasm
      - -s -w
      - -linkmode=external
    tags:
      - netgo
      - ledger
      - static_wasm

  - id: "med-linux-amd64"
    main: ./cmd/med
    binary: med
    hooks:
      pre:
        - wget https://github.com/CosmWasm/wasmvm/releases/download/{{ .Env.COSMWASM_VERSION }}/libwasmvm_muslc.x86_64.a -O /lib/libwasmvm_muslc.x86_64.a
        - cp /lib/libwasmvm_muslc.x86_64.a /lib/libwasmvm_muslc.a
        - curl -LO https://musl.cc/x86_64-linux-musl-cross.tgz
        - tar xf x86_64-linux-musl-cross.tgz
        - mv x86_64-linux-musl-cross /opt/musl-cross
    env:
      - CC=/opt/musl-cross/bin/x86_64-linux-musl-gcc
      - LD=/opt/musl-cross/bin/x86_64-linux-musl-ld
      - CGO_LDFLAGS=-L/lib
    goos:
      - linux
    goarch:
      - amd64
    flags:
      - -mod=readonly
      - -trimpath
    ldflags:
      - -X github.com/cosmos/cosmos-sdk/version.Name=me-hub
      - -X github.com/cosmos/cosmos-sdk/version.AppName=med
      - -X github.com/cosmos/cosmos-sdk/version.Version={{.Version}}
      - -X github.com/cosmos/cosmos-sdk/version.Commit={{.Commit}}
      - -X github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,ledger,muslc,osusergo
      - -s -w
      - -linkmode=external
      - -extldflags "-Wl,-z,muldefs -static"
    tags:
      - netgo
      - ledger
      - muslc
      - osusergo

#  - id: "med-linux-arm64"
#    main: ./cmd/med
#    binary: med
#    hooks:
#      pre:
#        - wget https://github.com/CosmWasm/wasmvm/releases/download/{{ .Env.COSMWASM_VERSION }}/libwasmvm_muslc.aarch64.a -O /usr/lib/libwasmvm_muslc.aarch64.a
#    env:
#      - CC=aarch64-linux-gnu-gcc
#      - CXX=aarch64-linux-gnu-g++
#    goos:
#      - linux
#    goarch:
#      - arm64
#    flags:
#      - -mod=readonly
#      - -trimpath
#    ldflags:
#      - -s -w
#      - -X github.com/cosmos/cosmos-sdk/version.Name=me-hub
#      - -X github.com/cosmos/cosmos-sdk/version.AppName=med
#      - -X github.com/cosmos/cosmos-sdk/version.Version={{.Version}}
#      - -X github.com/cosmos/cosmos-sdk/version.Commit={{.Commit}}
#      - -X github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,ledger,muslc,osusergo
#      - -w -s
#      - -linkmode=external
#      - -extldflags '-L/usr/lib -lwasmvm_muslc.aarch64 -Wl,-z,muldefs -lc -lrt -lpthread -lm --static'
#    tags:
#      - netgo
#      - ledger
#      - muslc
#      - osusergo

universal_binaries:
  - id: med-darwin-universal
    ids:
      - med-darwin-arm64
      - med-darwin-amd64
    replace: false
  - id: med-linux-universal
    ids:
      - med-linux-amd64
    replace: false

archives:
  - id: zipped
    builds:
      - med-darwin-amd64
      - med-darwin-arm64
      - med-linux-amd64
    name_template: "{{.ProjectName}}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    format: tar.gz
    files:
      - none*
#  - id: binaries
#    builds:
#      - med-darwin-amd64
#      - med-darwin-arm64
#      - med-linux-amd64
#    name_template: "{{.ProjectName}}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
#    format: binary
#    files:
#      - none*

checksum:
  name_template: SHA256SUMS-v{{.Version}}.txt
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
snapshot:
  name_template: "{{ .Tag }}-next"

release:
  draft: false
  replace_existing_draft: true
  prerelease: false
  mode: keep-existing
  header: |
    # me-hub {{ .Tag }} Release Notes
  footer: |
    ## 🔨 Build from source
    
    ```bash
    git clone https://github.com/openmetaearth/me-hub.git
    cd me-hub && git checkout {{ .Tag }}
    make install
    ```
    
    ## 🐳 Docker Images
    
    As an alternative to installing and running med on your system, you may run med in a Docker container.

    ```bash
    docker pull ghcr.io/openmetaearth/me-hub:{{ .Version }}
    ```
 
    Example run:

    ```bash
    docker run ghcr.io/openmetaearth/me-hub:{{ .Version }} version
    # v{{ .Version }}
    ````
    
    ## ⚡️ Download binaries
    
    Binaries for linux, darwin are available below.