with-expecter: true
recursive: true
filename: "mock_{{.InterfaceName}}.go"
dir: "{{.InterfaceDir}}/mock_{{.PackageName}}"
mockname: "Mock{{.InterfaceName}}"
outpkg: "mock_{{.PackageName}}"
inpackage: False
packages:
    github.com/cosmos/cosmos-sdk/x/mint/types:
        config:
            dir: 'x/wmint/types/mock_{{.PackageName}}'
        interfaces:
            AccountKeeper:
            StakingKeeper:
            BankKeeper:
            # select the interfaces you want mocked
    github.com/openmetaearth/me-hub/x/wdistri/types:
        config:
            all: True
    github.com/openmetaearth/me-hub/x/wstaking/types:
        interfaces:
            RegionI:
                #common interface
                config:
                    dir: 'testutil/mocks'
                    outpkg: 'mocks'

