services:
  node1:
    container_name: node1
    image: 192.168.0.79/me-hub/med:latest
    build:
      context: .
      dockerfile: Dockerfile_local
    command:
      - med
      - start
    restart: always
    ports:
      - 26657:36657
      - 26656:36656
      - 9090:8090
      - 1317:1318
      - 8545:9545
    volumes:
      - /Users/aris/.mechain:/root/.mechain
