FROM ubuntu:24.04

RUN apt-get update && \
    apt-get install -y ca-certificates tzdata libc6 wget && \
    rm -rf /var/lib/apt/lists/*

# Set the timezone to Asia/Shanghai
ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Cosmwasm - Download correct libwasmvm version (passed in from Makefile to stay in sync with go.mod)
ARG WASMVM_VERSION
RUN test -n "$WASMVM_VERSION" || (echo "WASMVM_VERSION build-arg is required" && exit 1) && \
    ARCH=$(uname -m) && \
    wget https://github.com/CosmWasm/wasmvm/releases/download/$WASMVM_VERSION/libwasmvm.$ARCH.so \
    -O /lib/libwasmvm.$ARCH.so && \
    # verify checksum
    wget https://github.com/CosmWasm/wasmvm/releases/download/$WASMVM_VERSION/checksums.txt -O /tmp/checksums.txt && \
    sha256sum /lib/libwasmvm.$ARCH.so | grep $(cat /tmp/checksums.txt | grep libwasmvm.$ARCH.so | cut -d ' ' -f 1)

COPY ./build/med /usr/local/bin/med
RUN chmod +x /usr/local/bin/med

WORKDIR /root
VOLUME ["/root"]

EXPOSE 26656/tcp 26657/tcp 26660/tcp 9090/tcp 1317/tcp 8545/tcp 8546/tcp
