package types

import (
	sdkerrors "github.com/cosmos/cosmos-sdk/types/errors"
)

var (
	ErrValidatorOwnerAddress      = sdkerrors.Register(ModuleName, 56, "cannot update validator owner address to module account address")
	ErrStakerShareExRateInvalid   = sdkerrors.Register(ModuleName, 57, "cannot delegate to validators with invalid (zero) ex-rate")
	ErrNoStakerForAddress         = sdkerrors.Register(ModuleName, 58, "staker does not contain stake")
	ErrMaxUnbondingStakeEntries   = sdkerrors.Register(ModuleName, 59, "too many unbonding stake entries for (staker, validator) tuple")
	ErrNotEnoughStakeShares       = sdkerrors.Register(ModuleName, 60, "not enough stake shares")
	ErrValidatorTokensAmount      = sdkerrors.Register(ModuleName, 61, "unstake limit: validator's tokens amount can not less than meid amount or delegate amount")
	ErrNoUnbondingStake           = sdkerrors.Register(ModuleName, 62, "no unbonding stake found")
	ErrNoStake                    = sdkerrors.Register(ModuleName, 63, "no stake for (address, validator) tuple")
	ErrCalculateInterest          = sdkerrors.Register(ModuleName, 64, "delegator calculate interest err.")
	ErrValidatorExist             = sdkerrors.Register(ModuleName, 65, "validator already exist")
	ErrValidatorAddress           = sdkerrors.Register(ModuleName, 66, "cannot update validator address to module account address")
	ErrValidatorRegionDuplication = sdkerrors.Register(ModuleName, 67, "validator region duplication err")

	ErrDoFixedDeposit           = sdkerrors.Register(ModuleName, 1113, "do fixed deposit error")
	ErrDoFixedWithDraw          = sdkerrors.Register(ModuleName, 1114, "do fixed withdraw error")
	ErrNoFixedDepositFound      = sdkerrors.Register(ModuleName, 1115, "fixed deposit not found")
	ErrFixedDepositNotExpired   = sdkerrors.Register(ModuleName, 1116, "fixed deposit not reach deadline")
	ErrFixedDepositInvalidPayee = sdkerrors.Register(ModuleName, 1117, "fixed deposit payee error")
	ErrPayInterest              = sdkerrors.Register(ModuleName, 1118, "pay interest err.")

	ErrAddFixedDepositConfig           = sdkerrors.Register(ModuleName, 1120, "add fixed deposit config error")
	ErrRemoveFixedDepositConfig        = sdkerrors.Register(ModuleName, 1121, "remove fixed deposit config error")
	ErrNoFixedDepositCountOfCfgFound   = sdkerrors.Register(ModuleName, 1122, "fixed deposit count under config not found")
	ErrFixedDepositCountOfCfgIsZero    = sdkerrors.Register(ModuleName, 1123, "fixed deposit count under config is zero")
	ErrFixedDepositConfigAlreadyExists = sdkerrors.Register(ModuleName, 1124, "fixed deposit config already exists")
	ErrFixedDepositExistUnderConfig    = sdkerrors.Register(ModuleName, 1125, "fixed deposit exists under this config")
	ErrSetFixedDepositConfigRate       = sdkerrors.Register(ModuleName, 1126, "set fixed deposit config rate error")
	ErrSetFixedDepositConfigStatus     = sdkerrors.Register(ModuleName, 1127, "set fixed deposit config status error")
	ErrFixedDepositConfigInactive      = sdkerrors.Register(ModuleName, 1128, "fixed deposit config status inactive")
	ErrFixedDepositConfigRateInvalid   = sdkerrors.Register(ModuleName, 1129, "fixed deposit config rate invalid, rate range:[0.0001, 10000]")

	ErrVaultAccountExists    = sdkerrors.Register(ModuleName, 1140, "region vault account exists")
	ErrSendCoinToRegionAdmin = sdkerrors.Register(ModuleName, 1141, "send coins to region admin error")
	ErrSendCoinToRegionVault = sdkerrors.Register(ModuleName, 1142, "send coins to region vault error")
	ErrSetRegionAnnualRate   = sdkerrors.Register(ModuleName, 1143, "set region annual rate error")
	ErrSendCoinToValOwner    = sdkerrors.Register(ModuleName, 1144, "send coins to validator owner error")
	ErrSendCoinToDevOperator = sdkerrors.Register(ModuleName, 1145, "send coins to dev operator error")
	ErrSendCoinToGlobalDao   = sdkerrors.Register(ModuleName, 1146, "send coins to global dao error")
	ErrGetGlobalDao          = sdkerrors.Register(ModuleName, 1147, "get global dao error")
	ErrCheckGlobalDao        = sdkerrors.Register(ModuleName, 1148, "invalid global dao")
	ErrKycNotExists          = sdkerrors.Register(ModuleName, 1149, "kyc not exists")
	ErrDidExists             = sdkerrors.Register(ModuleName, 1150, "did already exists")
	ErrDidNotExists          = sdkerrors.Register(ModuleName, 1151, "did not exists")
	ErrSendKycReward         = sdkerrors.Register(ModuleName, 1152, "send kyc reward")
	ErrRemoveKycReward       = sdkerrors.Register(ModuleName, 1153, "remove kyc reward")

	ErrRegionAlreadyExist       = sdkerrors.Register(ModuleName, 1162, "region already exist")
	ErrRegionNotExist           = sdkerrors.Register(ModuleName, 1163, "region not exist")
	ErrRegionValidatorNotExist  = sdkerrors.Register(ModuleName, 1164, "region validator not exist")
	ErrTransferRegion           = sdkerrors.Register(ModuleName, 1165, "transfer region err")
	ErrRegion                   = sdkerrors.Register(ModuleName, 1166, "region err")
	ErrExperienceRegionNotExist = sdkerrors.Register(ModuleName, 1167, "experience region not exist")
	ErrRemoveKyc                = sdkerrors.Register(ModuleName, 1168, "remove kyc not allowed")

	ErrAmountNotPositive        = sdkerrors.Register(ModuleName, 1171, "amount not positive")
	ErrAmountLessThanMin        = sdkerrors.Register(ModuleName, 1172, "amount is less than 0.01MEC")
	ErrRegionValidatorDuplicate = sdkerrors.Register(ModuleName, 1173, "input validator duplicates with already bonded validators")
	ErrRegionNameDuplicate      = sdkerrors.Register(ModuleName, 1174, "input region name duplicates with the name of existing region")
	ErrRegionName               = sdkerrors.Register(ModuleName, 1175, "invalid region name")
	ErrExpRegionNotExist        = sdkerrors.Register(ModuleName, 1176, "experience region not exist")

	ErrParameter           = sdkerrors.Register(ModuleName, 1201, "parameter error")
	ErrUnknownAccount      = sdkerrors.Register(ModuleName, 1202, "Unknown account")
	ErrInvalidRecordParams = sdkerrors.Register(ModuleName, 1203, "invalid record params")

	ErrValidatorDelegationAmount     = sdkerrors.Register(ModuleName, 1206, "Validator DelegationAmount less than requested value.")
	ErrNotEnoughDelegationAmount     = sdkerrors.Register(ModuleName, 1208, "not enough delegation amount")
	ErrMaxUnbondingDelegationEntries = sdkerrors.Register(ModuleName, 1209, "too many unbonding delegation entries for (delegator, validator) tuple")
	ErrNoDelegatorForAddress         = sdkerrors.Register(ModuleName, 1210, "delegator does not contain delegation")
	ErrNodeLimitExceeded             = sdkerrors.Register(ModuleName, 1211, "Node delegation limit exceeded.")
	ErrAssertionFailed               = sdkerrors.Register(ModuleName, 1212, "type Delegation assertion failed")
	ErrWithdrawDelegateReward        = sdkerrors.Register(ModuleName, 1213, "withdraw delegate reward failed")

	ErrEmptyDelegatorAddr       = sdkerrors.Register(ModuleName, 1214, "delegator address is empty")
	ErrEmptyWithdrawAddr        = sdkerrors.Register(ModuleName, 1215, "withdraw address is empty")
	ErrEmptyValidatorAddr       = sdkerrors.Register(ModuleName, 1216, "validator address is empty")
	ErrEmptyDelegationDistInfo  = sdkerrors.Register(ModuleName, 1217, "no delegation distribution info")
	ErrNoValidatorDistInfo      = sdkerrors.Register(ModuleName, 1218, "no validator distribution info")
	ErrNoValidatorCommission    = sdkerrors.Register(ModuleName, 1219, "no validator commission to withdraw")
	ErrSetWithdrawAddrDisabled  = sdkerrors.Register(ModuleName, 1220, "set withdraw address disabled")
	ErrBadDistribution          = sdkerrors.Register(ModuleName, 1221, "community pool does not have sufficient coins to distribute")
	ErrInvalidProposalAmount    = sdkerrors.Register(ModuleName, 1222, "invalid community pool spend proposal amount")
	ErrEmptyProposalRecipient   = sdkerrors.Register(ModuleName, 1223, "invalid community pool spend proposal recipient")
	ErrNoValidatorExists        = sdkerrors.Register(ModuleName, 1224, "validator does not exist")
	ErrNoDelegationExists       = sdkerrors.Register(ModuleName, 1225, "delegation does not exist")
	ErrAssertDelegation         = sdkerrors.Register(ModuleName, 1226, "The delegation structure assertion error.")
	ErrDistributionIncome       = sdkerrors.Register(ModuleName, 1227, "distribution income err.")
	ErrDistributionOther        = sdkerrors.Register(ModuleName, 1228, "distribution err.")
	ErrResetValidator           = sdkerrors.Register(ModuleName, 1229, "reset validator error")
	ErrHooks                    = sdkerrors.Register(ModuleName, 1301, "hooks error")
	ErrExistingReplaceValidator = sdkerrors.Register(ModuleName, 1302, "another validator replacement is already in progress")
	ErrValidatorNotBonded       = sdkerrors.Register(ModuleName, 1303, "only bonded validator can be replaced")

	ErrStakeOnValidatorIsEmpty = sdkerrors.Register(ModuleName, 1304, "stake on validator is empty")
	ErrProtoProc               = sdkerrors.Register(ModuleName, 1305, "proc proto error.")
	ErrInterProc               = sdkerrors.Register(ModuleName, 1306, "inter proc error.")
)
