package types

import (
	errorsmod "cosmossdk.io/errors"
)

var (
	ErrValidatorOwnerAddress      = errorsmod.Register(ModuleName, 56, "cannot update validator owner address to module account address")
	ErrStakerShareExRateInvalid   = errorsmod.Register(ModuleName, 57, "cannot delegate to validators with invalid (zero) ex-rate")
	ErrNoStakerForAddress         = errorsmod.Register(ModuleName, 58, "staker does not contain stake")
	ErrMaxUnbondingStakeEntries   = errorsmod.Register(ModuleName, 59, "too many unbonding stake entries for (staker, validator) tuple")
	ErrNotEnoughStakeShares       = errorsmod.Register(ModuleName, 60, "not enough stake shares")
	ErrValidatorTokensAmount      = errorsmod.Register(ModuleName, 61, "unstake limit: validator's tokens amount can not less than meid amount or delegate amount")
	ErrNoUnbondingStake           = errorsmod.Register(ModuleName, 62, "no unbonding stake found")
	ErrNoStake                    = errorsmod.Register(ModuleName, 63, "no stake for (address, validator) tuple")
	ErrCalculateInterest          = errorsmod.Register(ModuleName, 64, "delegator calculate interest err.")
	ErrValidatorExist             = errorsmod.Register(ModuleName, 65, "validator already exist")
	ErrValidatorAddress           = errorsmod.Register(ModuleName, 66, "cannot update validator address to module account address")
	ErrValidatorRegionDuplication = errorsmod.Register(ModuleName, 67, "validator region duplication err")

	ErrDoFixedDeposit           = errorsmod.Register(ModuleName, 1113, "do fixed deposit error")
	ErrDoFixedWithDraw          = errorsmod.Register(ModuleName, 1114, "do fixed withdraw error")
	ErrNoFixedDepositFound      = errorsmod.Register(ModuleName, 1115, "fixed deposit not found")
	ErrFixedDepositNotExpired   = errorsmod.Register(ModuleName, 1116, "fixed deposit not reach deadline")
	ErrFixedDepositInvalidPayee = errorsmod.Register(ModuleName, 1117, "fixed deposit payee error")
	ErrPayInterest              = errorsmod.Register(ModuleName, 1118, "pay interest err.")

	ErrAddFixedDepositConfig           = errorsmod.Register(ModuleName, 1120, "add fixed deposit config error")
	ErrRemoveFixedDepositConfig        = errorsmod.Register(ModuleName, 1121, "remove fixed deposit config error")
	ErrNoFixedDepositCountOfCfgFound   = errorsmod.Register(ModuleName, 1122, "fixed deposit count under config not found")
	ErrFixedDepositCountOfCfgIsZero    = errorsmod.Register(ModuleName, 1123, "fixed deposit count under config is zero")
	ErrFixedDepositConfigAlreadyExists = errorsmod.Register(ModuleName, 1124, "fixed deposit config already exists")
	ErrFixedDepositExistUnderConfig    = errorsmod.Register(ModuleName, 1125, "fixed deposit exists under this config")
	ErrSetFixedDepositConfigRate       = errorsmod.Register(ModuleName, 1126, "set fixed deposit config rate error")
	ErrSetFixedDepositConfigStatus     = errorsmod.Register(ModuleName, 1127, "set fixed deposit config status error")
	ErrFixedDepositConfigInactive      = errorsmod.Register(ModuleName, 1128, "fixed deposit config status inactive")
	ErrFixedDepositConfigRateInvalid   = errorsmod.Register(ModuleName, 1129, "fixed deposit config rate invalid, rate range:[0.0001, 10000]")

	ErrVaultAccountExists    = errorsmod.Register(ModuleName, 1140, "region vault account exists")
	ErrSendCoinToRegionAdmin = errorsmod.Register(ModuleName, 1141, "send coins to region admin error")
	ErrSendCoinToRegionVault = errorsmod.Register(ModuleName, 1142, "send coins to region vault error")
	ErrSetRegionAnnualRate   = errorsmod.Register(ModuleName, 1143, "set region annual rate error")
	ErrSendCoinToValOwner    = errorsmod.Register(ModuleName, 1144, "send coins to validator owner error")
	ErrSendCoinToDevOperator = errorsmod.Register(ModuleName, 1145, "send coins to region vault error")
	ErrSendCoinToGlobalAdmin = errorsmod.Register(ModuleName, 1146, "send coins to region vault error")
	ErrGetGlobalAdmin        = errorsmod.Register(ModuleName, 1147, "get global admin error")
	ErrCheckGlobalDao        = errorsmod.Register(ModuleName, 1148, "invalid global dao")
	ErrKycNotExists          = errorsmod.Register(ModuleName, 1149, "kyc not exists")
	ErrDidExists             = errorsmod.Register(ModuleName, 1150, "did already exists")
	ErrDidNotExists          = errorsmod.Register(ModuleName, 1151, "did not exists")
	ErrSendKycReward         = errorsmod.Register(ModuleName, 1152, "send kyc reward")
	ErrRemoveKycReward       = errorsmod.Register(ModuleName, 1153, "remove kyc reward")

	ErrRegionAlreadyExist       = errorsmod.Register(ModuleName, 1162, "region already exist")
	ErrRegionNotExist           = errorsmod.Register(ModuleName, 1163, "region not exist")
	ErrRegionValidatorNotExist  = errorsmod.Register(ModuleName, 1164, "region validator not exist")
	ErrTransferRegion           = errorsmod.Register(ModuleName, 1165, "transfer region err")
	ErrRegion                   = errorsmod.Register(ModuleName, 1166, "region err")
	ErrExperienceRegionNotExist = errorsmod.Register(ModuleName, 1167, "experience region not exist")
	ErrRemoveKyc                = errorsmod.Register(ModuleName, 1168, "remove kyc not allowed")

	ErrAmountNotPositive        = errorsmod.Register(ModuleName, 1171, "amount not positive")
	ErrAmountLessThanMin        = errorsmod.Register(ModuleName, 1172, "amount is less than 0.01ME")
	ErrRegionValidatorDuplicate = errorsmod.Register(ModuleName, 1173, "input validator duplicates with already bonded validators")
	ErrRegionNameDuplicate      = errorsmod.Register(ModuleName, 1174, "input region name duplicates with the name of existing region")
	ErrRegionName               = errorsmod.Register(ModuleName, 1175, "invalid region name")
	ErrExpRegionNotExist        = errorsmod.Register(ModuleName, 1176, "experience region not exist")

	ErrParameter           = errorsmod.Register(ModuleName, 1201, "parameter error")
	ErrUnknownAccount      = errorsmod.Register(ModuleName, 1202, "Unknown account")
	ErrInvalidRecordParams = errorsmod.Register(ModuleName, 1203, "invalid record params")

	ErrValidatorDelegationAmount     = errorsmod.Register(ModuleName, 1206, "Validator DelegationAmount less than requested value.")
	ErrNotEnoughDelegationAmount     = errorsmod.Register(ModuleName, 1208, "not enough delegation amount")
	ErrMaxUnbondingDelegationEntries = errorsmod.Register(ModuleName, 1209, "too many unbonding delegation entries for (delegator, validator) tuple")
	ErrNoDelegatorForAddress         = errorsmod.Register(ModuleName, 1210, "delegator does not contain delegation")
	ErrNodeLimitExceeded             = errorsmod.Register(ModuleName, 1211, "Node delegation limit exceeded.")
	ErrAssertionFailed               = errorsmod.Register(ModuleName, 1212, "type Delegation assertion failed")
	ErrWithdrawDelegateReward        = errorsmod.Register(ModuleName, 1213, "withdraw delegate reward failed")

	ErrEmptyDelegatorAddr       = errorsmod.Register(ModuleName, 1214, "delegator address is empty")
	ErrEmptyWithdrawAddr        = errorsmod.Register(ModuleName, 1215, "withdraw address is empty")
	ErrEmptyValidatorAddr       = errorsmod.Register(ModuleName, 1216, "validator address is empty")
	ErrEmptyDelegationDistInfo  = errorsmod.Register(ModuleName, 1217, "no delegation distribution info")
	ErrNoValidatorDistInfo      = errorsmod.Register(ModuleName, 1218, "no validator distribution info")
	ErrNoValidatorCommission    = errorsmod.Register(ModuleName, 1219, "no validator commission to withdraw")
	ErrSetWithdrawAddrDisabled  = errorsmod.Register(ModuleName, 1220, "set withdraw address disabled")
	ErrBadDistribution          = errorsmod.Register(ModuleName, 1221, "community pool does not have sufficient coins to distribute")
	ErrInvalidProposalAmount    = errorsmod.Register(ModuleName, 1222, "invalid community pool spend proposal amount")
	ErrEmptyProposalRecipient   = errorsmod.Register(ModuleName, 1223, "invalid community pool spend proposal recipient")
	ErrNoValidatorExists        = errorsmod.Register(ModuleName, 1224, "validator does not exist")
	ErrNoDelegationExists       = errorsmod.Register(ModuleName, 1225, "delegation does not exist")
	ErrAssertDelegation         = errorsmod.Register(ModuleName, 1226, "The delegation structure assertion error.")
	ErrDistributionIncome       = errorsmod.Register(ModuleName, 1227, "distribution income err.")
	ErrDistributionOther        = errorsmod.Register(ModuleName, 1228, "distribution err.")
	ErrResetValidator           = errorsmod.Register(ModuleName, 1229, "reset validator error")
	ErrHooks                    = errorsmod.Register(ModuleName, 1301, "hooks error")
	ErrExistingReplaceValidator = errorsmod.Register(ModuleName, 1302, "another validator replacement is already in progress")
	ErrValidatorNotBonded       = errorsmod.Register(ModuleName, 1303, "only bonded validator can be replaced")

	ErrStakeOnValidatorIsEmpty = errorsmod.Register(ModuleName, 1304, "stake on validator is empty")
	ErrProtoProc               = errorsmod.Register(ModuleName, 1305, "proc proto error.")
	ErrInterProc               = errorsmod.Register(ModuleName, 1306, "inter proc error.")
)
