package types

const (
	EventTypeUnstake                          = "unstake"
	EventTypeStake                            = "stake"
	EventTypeCompleteUnStakeBonding           = "complete_stake_unbonding"
	EventTypeCompleteUnDelBonding             = "complete_del_unbonding"
	EventTypeWithdrawDelegatorReward          = "withdraw_delegator_reward"
	EventTypeUnDelegate                       = "undelegate"
	EventTypeDoFixedDeposit                   = "fixed_deposit"
	EventTypeDoFixedWithDraw                  = "fixed_withdraw"
	EventTypeSettleDelRewardsForKyc           = "settle_del_rewards_for_kyc"
	EventTypeWithdrawFromRegion               = "withdraw_from_region"
	EventTypeWithdrawFromGlobalDaoFeePool     = "withdraw_from_global_dao_fee_pool"
	EventTypeNewKyc                           = "new_kyc"
	EventTypeRemoveKyc                        = "remove_kyc"
	EventTypeResetValidator                   = "reset_validator"
	EventTransferRegion                       = "transfer_region"
	EventTransferRegionSettlementFixedDeposit = "transfer_region_settlement_fixed_deposit"
	EventNewRegion                            = "new_region"
	EventNewNftClass                          = "new_nft_class"
	EventTypeDelegateTransfer                 = "delegate_transfer"
	EventTypeRemoveRegion                     = "remove_region"
	EventInviteReward                         = "invite_reward"
	EventTypeUpdateValidator                  = "update_validator"
	EventTypeGrantRegionWithdraw              = "grant_region_withdraw"
	EventTypeRevokeRegionWithdraw             = "revoke_region_withdraw"
)

const (
	AttributeKeyKycInviterRewardSender    = "invite_reward_sender"
	AttributeKeyKycInviter                = "inviter"
	AttributeKeyKycInvitee                = "invitee"
	AttributeKeyKycInviterReward          = "invite_reward"
	AttributeKeyCompletionTime            = "completion_time"
	AttributeKeyAccount                   = "account"
	AttributeKeyTerm                      = "fixed_deposit_config_term"
	AttributeKeyRate                      = "fixed_deposit_config_rate"
	AttributeKeyStatus                    = "fixed_deposit_config_status"
	AttributeKeyValidator                 = "validator"
	AttributeKeyStaker                    = "staker"
	AttributeKeyRewards                   = "rewards"
	AttributeKeyRegionTreasure            = "region_treasure"
	AttributeKeyNewShares                 = "new_shares"
	AttributeKeyTotalAmountDelegate       = "total_amount_delegate"
	AttributeKeyRegionId                  = "regionId"
	AttributeKeyAmountDelegateInterest    = "amount_of_delegate_interest"
	AttributeKeyDelegatorAddress          = "delegator_address"
	AttributeKeyPersonalDelegateInterest  = "personal_delegate_interest"
	AttributeKeyIsMeid                    = "is_meid"
	AttributeKeyDelegator                 = "delegator"
	AttributeKeyRegionTreasuryAddress     = "region_treasury_address"
	AttributeKeyPrincipal                 = "principal"
	AttributeKeyPrincipalAddr             = "principal_address"
	AttributeKeyStartTime                 = "start_time"
	AttributeKeyEndTime                   = "end_time"
	AttributeKeyId                        = "id"
	AttributeKeyInterest                  = "fixed_deposit_interest"
	AttributeKeyInterestAddr              = "fixed_deposit_interest_address"
	AttributeKeyTreasureAddr              = "fixed_deposit_treasure_address"
	AttributeKeyExpired                   = "fixed_expired"
	AttributeKeyCreator                   = "creator"
	AttributeKeyExecTime                  = "exec_time"
	AttributeKeyTransferAddress           = "transfer_address"
	AttributeKeyFromRegion                = "from_region"
	AttributeKeyToRegion                  = "to_region"
	AttributeKeyFixedDeposit              = "fixed_deposit_interest"
	AttributeKeyReceiver                  = "receiver"
	AttributeKeyKycRewardNodeAddress      = "kyc_reward_node_address"
	AttributeKeyKycRewardCommitteeAddress = "kyc_reward_committee_address"
	AttributeKeyMeidNumAddReward          = "meid_number_add_reward"
	AttributeKeyNewOwnerAddress           = "new_owner"
	AttributeKeyNewValidator              = "new_validator"
	AttributeKeyGrantedAddress            = "granted_address"
)
