// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: metaearth/eibc/lp.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	_ "github.com/openmetaearth/me-hub/x/common/types"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type OnDemandLP struct {
	// where funds come from, bech32-encoded
	FundsAddr string `protobuf:"bytes,1,opt,name=funds_addr,json=fundsAddr,proto3" json:"funds_addr,omitempty"`
	Rollapp   string `protobuf:"bytes,2,opt,name=rollapp,proto3" json:"rollapp,omitempty"`
	Denom     string `protobuf:"bytes,3,opt,name=denom,proto3" json:"denom,omitempty"`
	// will not fulfill if price is above this
	MaxPrice cosmossdk_io_math.Int `protobuf:"bytes,4,opt,name=maxPrice,proto3,customtype=cosmossdk.io/math.Int" json:"maxPrice"`
	// will not fulfill if fee is below this (percentage of price expressed in
	// [0,1])
	MinFee cosmossdk_io_math.LegacyDec `protobuf:"bytes,5,opt,name=minFee,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"minFee"`
	// will not fulfill if brings amt spent above limit
	SpendLimit cosmossdk_io_math.Int `protobuf:"bytes,6,opt,name=spendLimit,proto3,customtype=cosmossdk.io/math.Int" json:"spendLimit"`
	// will not fulfill orders which were created fewer than this blocks in the
	// past e.g. compatibility check occurs at height 7, order existed since block
	// 4,
	//      then fulfill if this field is 3 or less
	OrderMinAgeBlocks uint64 `protobuf:"varint,7,opt,name=orderMinAgeBlocks,proto3" json:"orderMinAgeBlocks,omitempty"`
}

func (m *OnDemandLP) Reset()         { *m = OnDemandLP{} }
func (m *OnDemandLP) String() string { return proto.CompactTextString(m) }
func (*OnDemandLP) ProtoMessage()    {}
func (*OnDemandLP) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d458f67a797a14e, []int{0}
}
func (m *OnDemandLP) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *OnDemandLP) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_OnDemandLP.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *OnDemandLP) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OnDemandLP.Merge(m, src)
}
func (m *OnDemandLP) XXX_Size() int {
	return m.Size()
}
func (m *OnDemandLP) XXX_DiscardUnknown() {
	xxx_messageInfo_OnDemandLP.DiscardUnknown(m)
}

var xxx_messageInfo_OnDemandLP proto.InternalMessageInfo

func (m *OnDemandLP) GetFundsAddr() string {
	if m != nil {
		return m.FundsAddr
	}
	return ""
}

func (m *OnDemandLP) GetRollapp() string {
	if m != nil {
		return m.Rollapp
	}
	return ""
}

func (m *OnDemandLP) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

func (m *OnDemandLP) GetOrderMinAgeBlocks() uint64 {
	if m != nil {
		return m.OrderMinAgeBlocks
	}
	return 0
}

type OnDemandLPRecord struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// amt spent so far
	Spent cosmossdk_io_math.Int `protobuf:"bytes,2,opt,name=spent,proto3,customtype=cosmossdk.io/math.Int" json:"spent"`
	Lp    *OnDemandLP           `protobuf:"bytes,3,opt,name=lp,proto3" json:"lp,omitempty"`
}

func (m *OnDemandLPRecord) Reset()         { *m = OnDemandLPRecord{} }
func (m *OnDemandLPRecord) String() string { return proto.CompactTextString(m) }
func (*OnDemandLPRecord) ProtoMessage()    {}
func (*OnDemandLPRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d458f67a797a14e, []int{1}
}
func (m *OnDemandLPRecord) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *OnDemandLPRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_OnDemandLPRecord.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *OnDemandLPRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OnDemandLPRecord.Merge(m, src)
}
func (m *OnDemandLPRecord) XXX_Size() int {
	return m.Size()
}
func (m *OnDemandLPRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_OnDemandLPRecord.DiscardUnknown(m)
}

var xxx_messageInfo_OnDemandLPRecord proto.InternalMessageInfo

func (m *OnDemandLPRecord) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *OnDemandLPRecord) GetLp() *OnDemandLP {
	if m != nil {
		return m.Lp
	}
	return nil
}

func init() {
	proto.RegisterType((*OnDemandLP)(nil), "metaearth.eibc.OnDemandLP")
	proto.RegisterType((*OnDemandLPRecord)(nil), "metaearth.eibc.OnDemandLPRecord")
}

func init() { proto.RegisterFile("metaearth/eibc/lp.proto", fileDescriptor_5d458f67a797a14e) }

var fileDescriptor_5d458f67a797a14e = []byte{
	// 462 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0xcd, 0x6a, 0xdb, 0x40,
	0x10, 0xb6, 0x54, 0xdb, 0x69, 0xb6, 0x10, 0xd2, 0x25, 0xa5, 0xaa, 0x4b, 0x94, 0x10, 0x28, 0x84,
	0x36, 0xd6, 0x92, 0xf6, 0xd0, 0xb3, 0x4d, 0x48, 0x09, 0x75, 0x49, 0xd0, 0xb1, 0x17, 0xb3, 0xda,
	0x9d, 0xca, 0x8b, 0xb5, 0x3f, 0x48, 0xeb, 0x92, 0xbc, 0x45, 0xfb, 0x2e, 0x79, 0x88, 0x1c, 0x43,
	0x4e, 0xa5, 0x87, 0x50, 0xec, 0x17, 0xe8, 0x23, 0x14, 0x6b, 0xb7, 0x76, 0x82, 0x4f, 0xbe, 0xe9,
	0xfb, 0xbe, 0x99, 0x6f, 0x66, 0x47, 0x1f, 0x7a, 0x29, 0xc1, 0x52, 0xa0, 0xa5, 0x1d, 0x11, 0x10,
	0x19, 0x23, 0x85, 0x49, 0x4c, 0xa9, 0xad, 0xc6, 0x5b, 0x0b, 0x21, 0x99, 0x0b, 0x9d, 0x98, 0xe9,
	0x4a, 0xea, 0x8a, 0x64, 0xb4, 0x02, 0xf2, 0xfd, 0x38, 0x03, 0x4b, 0x8f, 0x09, 0xd3, 0x42, 0xb9,
	0xfa, 0xce, 0x2b, 0xa7, 0x0f, 0x6b, 0x44, 0x1c, 0xf0, 0xd2, 0x4e, 0xae, 0x73, 0xed, 0xf8, 0xf9,
	0x97, 0x67, 0xdf, 0x2c, 0x27, 0x33, 0x2d, 0xa5, 0x56, 0xa4, 0xd4, 0x45, 0x41, 0x8d, 0x19, 0x1a,
	0xca, 0xc6, 0x60, 0x7d, 0xd9, 0xee, 0x4a, 0x59, 0x65, 0xa9, 0x9d, 0x78, 0xef, 0x83, 0xbf, 0x21,
	0x42, 0xe7, 0xea, 0x04, 0x24, 0x55, 0x7c, 0x70, 0x81, 0x77, 0x11, 0xfa, 0x36, 0x51, 0xbc, 0x1a,
	0x52, 0xce, 0xcb, 0x28, 0xd8, 0x0f, 0x0e, 0x37, 0xd3, 0xcd, 0x9a, 0xe9, 0x71, 0x5e, 0xe2, 0x08,
	0x6d, 0xf8, 0x21, 0x51, 0x58, 0x6b, 0xff, 0x21, 0xde, 0x41, 0x2d, 0x0e, 0x4a, 0xcb, 0xe8, 0x49,
	0xcd, 0x3b, 0x80, 0x3f, 0xa1, 0xa7, 0x92, 0x5e, 0x5e, 0x94, 0x82, 0x41, 0xd4, 0x9c, 0x0b, 0xfd,
	0x77, 0x37, 0xf7, 0x7b, 0x8d, 0xdf, 0xf7, 0x7b, 0x2f, 0xdc, 0x0b, 0x2b, 0x3e, 0x4e, 0x84, 0x26,
	0x92, 0xda, 0x51, 0x72, 0xa6, 0xec, 0xdd, 0x75, 0x17, 0xf9, 0xa7, 0x9f, 0x29, 0x9b, 0x2e, 0x9a,
	0xf1, 0x39, 0x6a, 0x4b, 0xa1, 0x4e, 0x01, 0xa2, 0x56, 0x6d, 0xf3, 0xd1, 0xdb, 0xbc, 0x5e, 0xb5,
	0x19, 0x40, 0x4e, 0xd9, 0xd5, 0x09, 0xb0, 0xbb, 0xeb, 0xee, 0xb6, 0x37, 0x5b, 0x70, 0xa9, 0xb7,
	0xc1, 0x9f, 0x11, 0xaa, 0x0c, 0x28, 0x3e, 0x10, 0x52, 0xd8, 0xa8, 0xbd, 0xfe, 0x6e, 0x0f, 0xda,
	0xf1, 0x11, 0x7a, 0xae, 0x4b, 0x0e, 0xe5, 0x17, 0xa1, 0x7a, 0x39, 0xf4, 0x0b, 0xcd, 0xc6, 0x55,
	0xb4, 0xb1, 0x1f, 0x1c, 0x36, 0xd3, 0x55, 0xe1, 0xe0, 0x67, 0x80, 0xb6, 0x97, 0x27, 0x4f, 0x81,
	0xe9, 0x92, 0xe3, 0x2d, 0x14, 0x0a, 0x5e, 0x1f, 0xbc, 0x99, 0x86, 0x82, 0xe3, 0x1e, 0x6a, 0xcd,
	0x07, 0x58, 0x77, 0xe7, 0xf5, 0x56, 0x73, 0x9d, 0xf8, 0x2d, 0x0a, 0x0b, 0x53, 0xff, 0x8f, 0x67,
	0xef, 0x3b, 0xc9, 0xe3, 0x38, 0x26, 0x0f, 0x16, 0x08, 0x0b, 0xd3, 0x3f, 0xbd, 0x99, 0xc6, 0xc1,
	0xed, 0x34, 0x0e, 0xfe, 0x4c, 0xe3, 0xe0, 0xc7, 0x2c, 0x6e, 0xdc, 0xce, 0xe2, 0xc6, 0xaf, 0x59,
	0xdc, 0xf8, 0x7a, 0x94, 0x0b, 0x3b, 0x9a, 0x64, 0x09, 0xd3, 0x92, 0x68, 0x03, 0x6a, 0x19, 0x27,
	0x09, 0xdd, 0xd1, 0x24, 0x23, 0x97, 0x2e, 0xf8, 0xf6, 0xca, 0x40, 0x95, 0xb5, 0xeb, 0x54, 0x7d,
	0xf8, 0x17, 0x00, 0x00, 0xff, 0xff, 0xcd, 0x51, 0x55, 0xd1, 0x17, 0x03, 0x00, 0x00,
}

func (m *OnDemandLP) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *OnDemandLP) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *OnDemandLP) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.OrderMinAgeBlocks != 0 {
		i = encodeVarintLp(dAtA, i, uint64(m.OrderMinAgeBlocks))
		i--
		dAtA[i] = 0x38
	}
	{
		size := m.SpendLimit.Size()
		i -= size
		if _, err := m.SpendLimit.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintLp(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	{
		size := m.MinFee.Size()
		i -= size
		if _, err := m.MinFee.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintLp(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	{
		size := m.MaxPrice.Size()
		i -= size
		if _, err := m.MaxPrice.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintLp(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintLp(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Rollapp) > 0 {
		i -= len(m.Rollapp)
		copy(dAtA[i:], m.Rollapp)
		i = encodeVarintLp(dAtA, i, uint64(len(m.Rollapp)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.FundsAddr) > 0 {
		i -= len(m.FundsAddr)
		copy(dAtA[i:], m.FundsAddr)
		i = encodeVarintLp(dAtA, i, uint64(len(m.FundsAddr)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *OnDemandLPRecord) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *OnDemandLPRecord) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *OnDemandLPRecord) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Lp != nil {
		{
			size, err := m.Lp.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintLp(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	{
		size := m.Spent.Size()
		i -= size
		if _, err := m.Spent.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintLp(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if m.Id != 0 {
		i = encodeVarintLp(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintLp(dAtA []byte, offset int, v uint64) int {
	offset -= sovLp(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *OnDemandLP) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.FundsAddr)
	if l > 0 {
		n += 1 + l + sovLp(uint64(l))
	}
	l = len(m.Rollapp)
	if l > 0 {
		n += 1 + l + sovLp(uint64(l))
	}
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovLp(uint64(l))
	}
	l = m.MaxPrice.Size()
	n += 1 + l + sovLp(uint64(l))
	l = m.MinFee.Size()
	n += 1 + l + sovLp(uint64(l))
	l = m.SpendLimit.Size()
	n += 1 + l + sovLp(uint64(l))
	if m.OrderMinAgeBlocks != 0 {
		n += 1 + sovLp(uint64(m.OrderMinAgeBlocks))
	}
	return n
}

func (m *OnDemandLPRecord) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovLp(uint64(m.Id))
	}
	l = m.Spent.Size()
	n += 1 + l + sovLp(uint64(l))
	if m.Lp != nil {
		l = m.Lp.Size()
		n += 1 + l + sovLp(uint64(l))
	}
	return n
}

func sovLp(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozLp(x uint64) (n int) {
	return sovLp(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *OnDemandLP) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLp
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: OnDemandLP: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: OnDemandLP: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FundsAddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLp
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLp
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLp
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FundsAddr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Rollapp", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLp
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLp
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLp
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Rollapp = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLp
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLp
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLp
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxPrice", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLp
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLp
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLp
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MaxPrice.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinFee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLp
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLp
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLp
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MinFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SpendLimit", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLp
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLp
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLp
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.SpendLimit.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OrderMinAgeBlocks", wireType)
			}
			m.OrderMinAgeBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLp
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.OrderMinAgeBlocks |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipLp(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthLp
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *OnDemandLPRecord) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLp
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: OnDemandLPRecord: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: OnDemandLPRecord: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLp
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Spent", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLp
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLp
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLp
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Spent.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Lp", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLp
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLp
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLp
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Lp == nil {
				m.Lp = &OnDemandLP{}
			}
			if err := m.Lp.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipLp(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthLp
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipLp(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowLp
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowLp
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowLp
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthLp
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupLp
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthLp
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthLp        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowLp          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupLp = fmt.Errorf("proto: unexpected end of group")
)
