// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: metaearth/sequencer/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_53d44c7ce1ea26c1, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_53d44c7ce1ea26c1, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryGetSequencerRequest struct {
	SequencerAddress string `protobuf:"bytes,1,opt,name=sequencerAddress,proto3" json:"sequencerAddress,omitempty"`
}

func (m *QueryGetSequencerRequest) Reset()         { *m = QueryGetSequencerRequest{} }
func (m *QueryGetSequencerRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetSequencerRequest) ProtoMessage()    {}
func (*QueryGetSequencerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_53d44c7ce1ea26c1, []int{2}
}
func (m *QueryGetSequencerRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetSequencerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetSequencerRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetSequencerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetSequencerRequest.Merge(m, src)
}
func (m *QueryGetSequencerRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetSequencerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetSequencerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetSequencerRequest proto.InternalMessageInfo

func (m *QueryGetSequencerRequest) GetSequencerAddress() string {
	if m != nil {
		return m.SequencerAddress
	}
	return ""
}

type QueryGetSequencerResponse struct {
	Sequencer Sequencer `protobuf:"bytes,1,opt,name=sequencer,proto3" json:"sequencer"`
}

func (m *QueryGetSequencerResponse) Reset()         { *m = QueryGetSequencerResponse{} }
func (m *QueryGetSequencerResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetSequencerResponse) ProtoMessage()    {}
func (*QueryGetSequencerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_53d44c7ce1ea26c1, []int{3}
}
func (m *QueryGetSequencerResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetSequencerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetSequencerResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetSequencerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetSequencerResponse.Merge(m, src)
}
func (m *QueryGetSequencerResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetSequencerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetSequencerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetSequencerResponse proto.InternalMessageInfo

func (m *QueryGetSequencerResponse) GetSequencer() Sequencer {
	if m != nil {
		return m.Sequencer
	}
	return Sequencer{}
}

type QuerySequencersRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QuerySequencersRequest) Reset()         { *m = QuerySequencersRequest{} }
func (m *QuerySequencersRequest) String() string { return proto.CompactTextString(m) }
func (*QuerySequencersRequest) ProtoMessage()    {}
func (*QuerySequencersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_53d44c7ce1ea26c1, []int{4}
}
func (m *QuerySequencersRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QuerySequencersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QuerySequencersRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QuerySequencersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuerySequencersRequest.Merge(m, src)
}
func (m *QuerySequencersRequest) XXX_Size() int {
	return m.Size()
}
func (m *QuerySequencersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QuerySequencersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QuerySequencersRequest proto.InternalMessageInfo

func (m *QuerySequencersRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QuerySequencersResponse struct {
	Sequencers []Sequencer         `protobuf:"bytes,1,rep,name=sequencers,proto3" json:"sequencers"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QuerySequencersResponse) Reset()         { *m = QuerySequencersResponse{} }
func (m *QuerySequencersResponse) String() string { return proto.CompactTextString(m) }
func (*QuerySequencersResponse) ProtoMessage()    {}
func (*QuerySequencersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_53d44c7ce1ea26c1, []int{5}
}
func (m *QuerySequencersResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QuerySequencersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QuerySequencersResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QuerySequencersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuerySequencersResponse.Merge(m, src)
}
func (m *QuerySequencersResponse) XXX_Size() int {
	return m.Size()
}
func (m *QuerySequencersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QuerySequencersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QuerySequencersResponse proto.InternalMessageInfo

func (m *QuerySequencersResponse) GetSequencers() []Sequencer {
	if m != nil {
		return m.Sequencers
	}
	return nil
}

func (m *QuerySequencersResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryGetSequencersByRollappRequest struct {
	RollappId string `protobuf:"bytes,1,opt,name=rollappId,proto3" json:"rollappId,omitempty"`
}

func (m *QueryGetSequencersByRollappRequest) Reset()         { *m = QueryGetSequencersByRollappRequest{} }
func (m *QueryGetSequencersByRollappRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetSequencersByRollappRequest) ProtoMessage()    {}
func (*QueryGetSequencersByRollappRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_53d44c7ce1ea26c1, []int{6}
}
func (m *QueryGetSequencersByRollappRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetSequencersByRollappRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetSequencersByRollappRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetSequencersByRollappRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetSequencersByRollappRequest.Merge(m, src)
}
func (m *QueryGetSequencersByRollappRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetSequencersByRollappRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetSequencersByRollappRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetSequencersByRollappRequest proto.InternalMessageInfo

func (m *QueryGetSequencersByRollappRequest) GetRollappId() string {
	if m != nil {
		return m.RollappId
	}
	return ""
}

type QueryGetSequencersByRollappResponse struct {
	Sequencers []Sequencer `protobuf:"bytes,1,rep,name=sequencers,proto3" json:"sequencers"`
}

func (m *QueryGetSequencersByRollappResponse) Reset()         { *m = QueryGetSequencersByRollappResponse{} }
func (m *QueryGetSequencersByRollappResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetSequencersByRollappResponse) ProtoMessage()    {}
func (*QueryGetSequencersByRollappResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_53d44c7ce1ea26c1, []int{7}
}
func (m *QueryGetSequencersByRollappResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetSequencersByRollappResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetSequencersByRollappResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetSequencersByRollappResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetSequencersByRollappResponse.Merge(m, src)
}
func (m *QueryGetSequencersByRollappResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetSequencersByRollappResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetSequencersByRollappResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetSequencersByRollappResponse proto.InternalMessageInfo

func (m *QueryGetSequencersByRollappResponse) GetSequencers() []Sequencer {
	if m != nil {
		return m.Sequencers
	}
	return nil
}

type QueryGetSequencersByRollappByStatusRequest struct {
	RollappId string          `protobuf:"bytes,1,opt,name=rollappId,proto3" json:"rollappId,omitempty"`
	Status    OperatingStatus `protobuf:"varint,2,opt,name=status,proto3,enum=metaearth.sequencer.OperatingStatus" json:"status,omitempty"`
}

func (m *QueryGetSequencersByRollappByStatusRequest) Reset() {
	*m = QueryGetSequencersByRollappByStatusRequest{}
}
func (m *QueryGetSequencersByRollappByStatusRequest) String() string {
	return proto.CompactTextString(m)
}
func (*QueryGetSequencersByRollappByStatusRequest) ProtoMessage() {}
func (*QueryGetSequencersByRollappByStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_53d44c7ce1ea26c1, []int{8}
}
func (m *QueryGetSequencersByRollappByStatusRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetSequencersByRollappByStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetSequencersByRollappByStatusRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetSequencersByRollappByStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetSequencersByRollappByStatusRequest.Merge(m, src)
}
func (m *QueryGetSequencersByRollappByStatusRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetSequencersByRollappByStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetSequencersByRollappByStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetSequencersByRollappByStatusRequest proto.InternalMessageInfo

func (m *QueryGetSequencersByRollappByStatusRequest) GetRollappId() string {
	if m != nil {
		return m.RollappId
	}
	return ""
}

func (m *QueryGetSequencersByRollappByStatusRequest) GetStatus() OperatingStatus {
	if m != nil {
		return m.Status
	}
	return Unbonded
}

type QueryGetSequencersByRollappByStatusResponse struct {
	Sequencers []Sequencer `protobuf:"bytes,1,rep,name=sequencers,proto3" json:"sequencers"`
}

func (m *QueryGetSequencersByRollappByStatusResponse) Reset() {
	*m = QueryGetSequencersByRollappByStatusResponse{}
}
func (m *QueryGetSequencersByRollappByStatusResponse) String() string {
	return proto.CompactTextString(m)
}
func (*QueryGetSequencersByRollappByStatusResponse) ProtoMessage() {}
func (*QueryGetSequencersByRollappByStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_53d44c7ce1ea26c1, []int{9}
}
func (m *QueryGetSequencersByRollappByStatusResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetSequencersByRollappByStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetSequencersByRollappByStatusResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetSequencersByRollappByStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetSequencersByRollappByStatusResponse.Merge(m, src)
}
func (m *QueryGetSequencersByRollappByStatusResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetSequencersByRollappByStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetSequencersByRollappByStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetSequencersByRollappByStatusResponse proto.InternalMessageInfo

func (m *QueryGetSequencersByRollappByStatusResponse) GetSequencers() []Sequencer {
	if m != nil {
		return m.Sequencers
	}
	return nil
}

type QueryGetUnConfirmSequencersAddrByRollappRequest struct {
	RollappId   string `protobuf:"bytes,1,opt,name=rollappId,proto3" json:"rollappId,omitempty"`
	BlockHeight int64  `protobuf:"varint,2,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
}

func (m *QueryGetUnConfirmSequencersAddrByRollappRequest) Reset() {
	*m = QueryGetUnConfirmSequencersAddrByRollappRequest{}
}
func (m *QueryGetUnConfirmSequencersAddrByRollappRequest) String() string {
	return proto.CompactTextString(m)
}
func (*QueryGetUnConfirmSequencersAddrByRollappRequest) ProtoMessage() {}
func (*QueryGetUnConfirmSequencersAddrByRollappRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_53d44c7ce1ea26c1, []int{10}
}
func (m *QueryGetUnConfirmSequencersAddrByRollappRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetUnConfirmSequencersAddrByRollappRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetUnConfirmSequencersAddrByRollappRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetUnConfirmSequencersAddrByRollappRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetUnConfirmSequencersAddrByRollappRequest.Merge(m, src)
}
func (m *QueryGetUnConfirmSequencersAddrByRollappRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetUnConfirmSequencersAddrByRollappRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetUnConfirmSequencersAddrByRollappRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetUnConfirmSequencersAddrByRollappRequest proto.InternalMessageInfo

func (m *QueryGetUnConfirmSequencersAddrByRollappRequest) GetRollappId() string {
	if m != nil {
		return m.RollappId
	}
	return ""
}

func (m *QueryGetUnConfirmSequencersAddrByRollappRequest) GetBlockHeight() int64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

type QueryGetUnConfirmSequencersAddrByRollappResponse struct {
	NewSequencer         Sequencer `protobuf:"bytes,1,opt,name=new_sequencer,json=newSequencer,proto3" json:"new_sequencer"`
	StartHeight          int64     `protobuf:"varint,2,opt,name=start_height,json=startHeight,proto3" json:"start_height,omitempty"`
	UnconfirmCacheHeight int64     `protobuf:"varint,3,opt,name=unconfirm_cache_height,json=unconfirmCacheHeight,proto3" json:"unconfirm_cache_height,omitempty"`
}

func (m *QueryGetUnConfirmSequencersAddrByRollappResponse) Reset() {
	*m = QueryGetUnConfirmSequencersAddrByRollappResponse{}
}
func (m *QueryGetUnConfirmSequencersAddrByRollappResponse) String() string {
	return proto.CompactTextString(m)
}
func (*QueryGetUnConfirmSequencersAddrByRollappResponse) ProtoMessage() {}
func (*QueryGetUnConfirmSequencersAddrByRollappResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_53d44c7ce1ea26c1, []int{11}
}
func (m *QueryGetUnConfirmSequencersAddrByRollappResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetUnConfirmSequencersAddrByRollappResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetUnConfirmSequencersAddrByRollappResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetUnConfirmSequencersAddrByRollappResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetUnConfirmSequencersAddrByRollappResponse.Merge(m, src)
}
func (m *QueryGetUnConfirmSequencersAddrByRollappResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetUnConfirmSequencersAddrByRollappResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetUnConfirmSequencersAddrByRollappResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetUnConfirmSequencersAddrByRollappResponse proto.InternalMessageInfo

func (m *QueryGetUnConfirmSequencersAddrByRollappResponse) GetNewSequencer() Sequencer {
	if m != nil {
		return m.NewSequencer
	}
	return Sequencer{}
}

func (m *QueryGetUnConfirmSequencersAddrByRollappResponse) GetStartHeight() int64 {
	if m != nil {
		return m.StartHeight
	}
	return 0
}

func (m *QueryGetUnConfirmSequencersAddrByRollappResponse) GetUnconfirmCacheHeight() int64 {
	if m != nil {
		return m.UnconfirmCacheHeight
	}
	return 0
}

type QueryReplaceProposerInfoRequest struct {
	RollappId string `protobuf:"bytes,1,opt,name=rollappId,proto3" json:"rollappId,omitempty"`
}

func (m *QueryReplaceProposerInfoRequest) Reset()         { *m = QueryReplaceProposerInfoRequest{} }
func (m *QueryReplaceProposerInfoRequest) String() string { return proto.CompactTextString(m) }
func (*QueryReplaceProposerInfoRequest) ProtoMessage()    {}
func (*QueryReplaceProposerInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_53d44c7ce1ea26c1, []int{12}
}
func (m *QueryReplaceProposerInfoRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryReplaceProposerInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryReplaceProposerInfoRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryReplaceProposerInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryReplaceProposerInfoRequest.Merge(m, src)
}
func (m *QueryReplaceProposerInfoRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryReplaceProposerInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryReplaceProposerInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryReplaceProposerInfoRequest proto.InternalMessageInfo

func (m *QueryReplaceProposerInfoRequest) GetRollappId() string {
	if m != nil {
		return m.RollappId
	}
	return ""
}

type QueryReplaceProposerInfoResponse struct {
	ReplaceProposer MsgStoreReplaceProposer `protobuf:"bytes,1,opt,name=replace_proposer,json=replaceProposer,proto3" json:"replace_proposer"`
}

func (m *QueryReplaceProposerInfoResponse) Reset()         { *m = QueryReplaceProposerInfoResponse{} }
func (m *QueryReplaceProposerInfoResponse) String() string { return proto.CompactTextString(m) }
func (*QueryReplaceProposerInfoResponse) ProtoMessage()    {}
func (*QueryReplaceProposerInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_53d44c7ce1ea26c1, []int{13}
}
func (m *QueryReplaceProposerInfoResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryReplaceProposerInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryReplaceProposerInfoResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryReplaceProposerInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryReplaceProposerInfoResponse.Merge(m, src)
}
func (m *QueryReplaceProposerInfoResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryReplaceProposerInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryReplaceProposerInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryReplaceProposerInfoResponse proto.InternalMessageInfo

func (m *QueryReplaceProposerInfoResponse) GetReplaceProposer() MsgStoreReplaceProposer {
	if m != nil {
		return m.ReplaceProposer
	}
	return MsgStoreReplaceProposer{}
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "metaearth.sequencer.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "metaearth.sequencer.QueryParamsResponse")
	proto.RegisterType((*QueryGetSequencerRequest)(nil), "metaearth.sequencer.QueryGetSequencerRequest")
	proto.RegisterType((*QueryGetSequencerResponse)(nil), "metaearth.sequencer.QueryGetSequencerResponse")
	proto.RegisterType((*QuerySequencersRequest)(nil), "metaearth.sequencer.QuerySequencersRequest")
	proto.RegisterType((*QuerySequencersResponse)(nil), "metaearth.sequencer.QuerySequencersResponse")
	proto.RegisterType((*QueryGetSequencersByRollappRequest)(nil), "metaearth.sequencer.QueryGetSequencersByRollappRequest")
	proto.RegisterType((*QueryGetSequencersByRollappResponse)(nil), "metaearth.sequencer.QueryGetSequencersByRollappResponse")
	proto.RegisterType((*QueryGetSequencersByRollappByStatusRequest)(nil), "metaearth.sequencer.QueryGetSequencersByRollappByStatusRequest")
	proto.RegisterType((*QueryGetSequencersByRollappByStatusResponse)(nil), "metaearth.sequencer.QueryGetSequencersByRollappByStatusResponse")
	proto.RegisterType((*QueryGetUnConfirmSequencersAddrByRollappRequest)(nil), "metaearth.sequencer.QueryGetUnConfirmSequencersAddrByRollappRequest")
	proto.RegisterType((*QueryGetUnConfirmSequencersAddrByRollappResponse)(nil), "metaearth.sequencer.QueryGetUnConfirmSequencersAddrByRollappResponse")
	proto.RegisterType((*QueryReplaceProposerInfoRequest)(nil), "metaearth.sequencer.QueryReplaceProposerInfoRequest")
	proto.RegisterType((*QueryReplaceProposerInfoResponse)(nil), "metaearth.sequencer.QueryReplaceProposerInfoResponse")
}

func init() { proto.RegisterFile("metaearth/sequencer/query.proto", fileDescriptor_53d44c7ce1ea26c1) }

var fileDescriptor_53d44c7ce1ea26c1 = []byte{
	// 930 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0x4f, 0x6f, 0xdc, 0x44,
	0x14, 0x8f, 0x13, 0x88, 0x94, 0xd7, 0x02, 0xd5, 0x24, 0x2a, 0xc5, 0x29, 0x4e, 0x70, 0x50, 0x5b,
	0x6d, 0x5b, 0x9b, 0xa4, 0x05, 0x5a, 0x09, 0x11, 0xba, 0x2d, 0x0d, 0x11, 0x42, 0x84, 0x8d, 0x40,
	0x08, 0x09, 0xcc, 0xac, 0x33, 0xf1, 0x5a, 0xdd, 0xf5, 0xb8, 0x33, 0xb3, 0x94, 0x55, 0xb4, 0x12,
	0x70, 0xe2, 0x06, 0x12, 0x27, 0x3e, 0x00, 0x12, 0x9f, 0x83, 0x53, 0x8e, 0x95, 0x90, 0x10, 0x07,
	0x84, 0x50, 0xc2, 0x85, 0x6f, 0x81, 0x3c, 0x33, 0xb6, 0x77, 0xd7, 0xde, 0xad, 0x37, 0xcd, 0xcd,
	0x7a, 0xf3, 0xfe, 0xfc, 0x7e, 0xbf, 0x79, 0xf3, 0x9e, 0x61, 0xa5, 0x43, 0x04, 0x26, 0x98, 0x89,
	0x96, 0xcb, 0xc9, 0xc3, 0x2e, 0x89, 0x7c, 0xc2, 0xdc, 0x87, 0x5d, 0xc2, 0x7a, 0x4e, 0xcc, 0xa8,
	0xa0, 0x68, 0x31, 0x73, 0x70, 0x32, 0x07, 0xb3, 0xe6, 0x53, 0xde, 0xa1, 0xdc, 0x6d, 0x62, 0x4e,
	0x94, 0xb7, 0xfb, 0xd5, 0x7a, 0x93, 0x08, 0xbc, 0xee, 0xc6, 0x38, 0x08, 0x23, 0x2c, 0x42, 0x1a,
	0xa9, 0x04, 0xe6, 0x52, 0x40, 0x03, 0x2a, 0x3f, 0xdd, 0xe4, 0x4b, 0x5b, 0x2f, 0x06, 0x94, 0x06,
	0x6d, 0xe2, 0xe2, 0x38, 0x74, 0x71, 0x14, 0x51, 0x21, 0x43, 0xb8, 0x3e, 0xad, 0x95, 0xa1, 0xa2,
	0x31, 0x61, 0x58, 0x84, 0x51, 0xe0, 0x71, 0x81, 0x45, 0x37, 0xf5, 0x5d, 0x2d, 0xf3, 0x8d, 0x31,
	0xc3, 0x9d, 0xd4, 0x63, 0xad, 0xcc, 0x23, 0xfb, 0x52, 0x4e, 0xf6, 0x12, 0xa0, 0x8f, 0x12, 0x22,
	0x3b, 0x32, 0xb2, 0x91, 0x9c, 0x72, 0x61, 0xef, 0xc0, 0xe2, 0x90, 0x95, 0xc7, 0x34, 0xe2, 0x04,
	0xdd, 0x86, 0x79, 0x55, 0xe1, 0x82, 0xb1, 0x6a, 0x5c, 0x39, 0xb3, 0xb1, 0xec, 0x94, 0xa8, 0xe4,
	0xa8, 0xa0, 0xfa, 0x33, 0x87, 0x7f, 0xaf, 0xcc, 0x34, 0x74, 0x80, 0x7d, 0x1f, 0x2e, 0xc8, 0x8c,
	0x5b, 0x44, 0xec, 0xa6, 0x9e, 0xba, 0x1a, 0xaa, 0xc1, 0xb9, 0x2c, 0xfa, 0xce, 0xde, 0x1e, 0x23,
	0x5c, 0x15, 0x58, 0x68, 0x14, 0xec, 0xb6, 0x07, 0x2f, 0x95, 0xe4, 0xd1, 0xf8, 0xea, 0xb0, 0x90,
	0x05, 0x68, 0x88, 0x56, 0x29, 0xc4, 0x2c, 0x54, 0xa3, 0xcc, 0xc3, 0xec, 0x2f, 0xe1, 0xbc, 0x2c,
	0x90, 0xb9, 0xa4, 0xa2, 0xa0, 0xfb, 0x00, 0xf9, 0x2d, 0xeb, 0xf4, 0x97, 0x1c, 0xd5, 0x12, 0x4e,
	0xd2, 0x12, 0x8e, 0x6a, 0x20, 0xdd, 0x12, 0xce, 0x0e, 0x0e, 0x88, 0x8e, 0x6d, 0x0c, 0x44, 0xda,
	0xbf, 0x1a, 0xf0, 0x62, 0xa1, 0x84, 0x66, 0x70, 0x0f, 0x20, 0x83, 0x92, 0x88, 0x30, 0x57, 0x99,
	0xc2, 0x40, 0x1c, 0xda, 0x1a, 0x42, 0x3a, 0x2b, 0x91, 0x5e, 0x7e, 0x22, 0x52, 0x05, 0x61, 0x08,
	0x6a, 0x1d, 0xec, 0x82, 0xda, 0xbc, 0xde, 0x6b, 0xd0, 0x76, 0x1b, 0xc7, 0x71, 0x2a, 0xcc, 0x45,
	0x58, 0x60, 0xca, 0xb2, 0xbd, 0xa7, 0x2f, 0x2e, 0x37, 0xd8, 0x0f, 0x60, 0x6d, 0x62, 0x8e, 0xd3,
	0x64, 0x6e, 0x7f, 0x6f, 0x40, 0x6d, 0x42, 0xb5, 0x7a, 0x6f, 0x57, 0xbe, 0xa1, 0x4a, 0xc8, 0xd1,
	0x5b, 0x30, 0xaf, 0x9e, 0x9c, 0x94, 0xf0, 0xf9, 0x8d, 0x57, 0x4b, 0xe1, 0x7c, 0x98, 0xbe, 0x4f,
	0x9d, 0x5a, 0xc7, 0xd8, 0x1c, 0xae, 0x56, 0x42, 0x72, 0xaa, 0xfc, 0x19, 0xb8, 0x69, 0xd1, 0x8f,
	0xa3, 0xbb, 0x34, 0xda, 0x0f, 0x59, 0x27, 0xaf, 0x9e, 0x3c, 0xa2, 0xe9, 0x6e, 0x0f, 0xbd, 0x02,
	0x67, 0x9b, 0x6d, 0xea, 0x3f, 0xf0, 0x5a, 0x24, 0x0c, 0x5a, 0x42, 0x2a, 0x31, 0xd7, 0x38, 0x23,
	0x6d, 0xef, 0x49, 0x93, 0xfd, 0x87, 0x01, 0xaf, 0x55, 0x2f, 0xaa, 0xe9, 0x6e, 0xc3, 0x73, 0x11,
	0x79, 0xe4, 0x9d, 0xec, 0xb9, 0x9e, 0x8d, 0xc8, 0xa3, 0xcc, 0x96, 0x40, 0xe4, 0x02, 0x33, 0x31,
	0x02, 0x51, 0xda, 0x14, 0x44, 0x74, 0x13, 0xce, 0x77, 0x23, 0x5f, 0x21, 0xf3, 0x7c, 0xec, 0xb7,
	0x48, 0xea, 0x3c, 0x27, 0x9d, 0x97, 0xb2, 0xd3, 0xbb, 0xc9, 0xa1, 0x26, 0xb6, 0x09, 0x2b, 0x92,
	0x57, 0x83, 0xc4, 0x6d, 0xec, 0x93, 0x1d, 0x46, 0x63, 0xca, 0x09, 0xdb, 0x8e, 0xf6, 0x69, 0xb5,
	0xd6, 0xff, 0xd6, 0x80, 0xd5, 0xf1, 0x19, 0xb4, 0x12, 0x9f, 0xc3, 0x39, 0xa6, 0x8e, 0xbd, 0x58,
	0x9f, 0x6b, 0x31, 0xae, 0x95, 0x8a, 0xf1, 0x01, 0x0f, 0x76, 0x05, 0x65, 0x64, 0x24, 0xa7, 0x96,
	0xe6, 0x05, 0x36, 0x6c, 0xde, 0xf8, 0x0b, 0xe0, 0x59, 0x89, 0x01, 0x7d, 0x63, 0xc0, 0xbc, 0x9a,
	0xcd, 0xe8, 0x72, 0x69, 0xe6, 0xe2, 0x22, 0x30, 0xaf, 0x3c, 0xd9, 0x51, 0xd1, 0xb0, 0xd7, 0xbe,
	0xfb, 0xfd, 0xdf, 0x9f, 0x66, 0x5f, 0x46, 0xcb, 0xee, 0xf8, 0xc5, 0x84, 0x7e, 0x31, 0x60, 0x21,
	0xbf, 0xb8, 0xeb, 0xe3, 0x93, 0x97, 0xac, 0x09, 0xd3, 0xa9, 0xea, 0xae, 0x11, 0xdd, 0x96, 0x88,
	0x6e, 0xa0, 0x75, 0x77, 0xe2, 0x22, 0x74, 0x0f, 0x46, 0x97, 0x4c, 0x1f, 0xfd, 0x60, 0x00, 0xe4,
	0x1d, 0x8c, 0xae, 0x8e, 0xaf, 0x5c, 0x58, 0x13, 0xe6, 0xb5, 0x6a, 0xce, 0x1a, 0xe4, 0x25, 0x09,
	0x72, 0x15, 0x59, 0x93, 0x41, 0xa2, 0x43, 0x03, 0x16, 0x4b, 0xc6, 0x08, 0x7a, 0xb3, 0x9a, 0x28,
	0x85, 0xa1, 0x6d, 0xde, 0x9a, 0x3e, 0x50, 0x43, 0x7e, 0x5b, 0x42, 0xbe, 0x85, 0xde, 0x98, 0x0c,
	0x99, 0x7b, 0xcd, 0x9e, 0xa7, 0xdf, 0x82, 0x7b, 0x90, 0x3d, 0x8a, 0x3e, 0xfa, 0xcf, 0x80, 0xe5,
	0x09, 0x13, 0x11, 0x6d, 0x4e, 0x8b, 0x6c, 0x64, 0xaa, 0x9b, 0xef, 0x9c, 0x3c, 0x81, 0xa6, 0xb8,
	0x25, 0x29, 0xde, 0x41, 0x9b, 0x27, 0xa3, 0xe8, 0x1e, 0xa8, 0x1d, 0xd0, 0x47, 0x3f, 0xcf, 0x42,
	0xad, 0x38, 0x13, 0x75, 0x9f, 0x15, 0xa9, 0xdf, 0x9b, 0x88, 0xbc, 0xe2, 0x44, 0x37, 0xdf, 0x7d,
	0xca, 0x2c, 0x5a, 0x84, 0x2f, 0xa4, 0x08, 0x9f, 0xa2, 0x4f, 0x4a, 0x45, 0xc8, 0xe7, 0x69, 0x66,
	0xf3, 0xb0, 0xe2, 0x35, 0x56, 0x95, 0xc1, 0x4d, 0xd2, 0x47, 0xbf, 0x19, 0xb0, 0x58, 0x32, 0x18,
	0xd1, 0xcd, 0xf1, 0xf0, 0xc7, 0x4f, 0x62, 0xf3, 0xf5, 0x29, 0xa3, 0x86, 0x9b, 0xd9, 0x2e, 0x6f,
	0xe6, 0xd1, 0xc1, 0xec, 0x85, 0xd1, 0x3e, 0x1d, 0xe4, 0x54, 0x7f, 0xff, 0xf0, 0xc8, 0x32, 0x1e,
	0x1f, 0x59, 0xc6, 0x3f, 0x47, 0x96, 0xf1, 0xe3, 0xb1, 0x35, 0xf3, 0xf8, 0xd8, 0x9a, 0xf9, 0xf3,
	0xd8, 0x9a, 0xf9, 0x6c, 0x3d, 0x08, 0x45, 0xab, 0xdb, 0x74, 0x7c, 0xda, 0x49, 0xfe, 0xe1, 0xa3,
	0x3c, 0x7f, 0x87, 0x5c, 0x6f, 0x75, 0x9b, 0xee, 0xd7, 0x03, 0x85, 0x44, 0x2f, 0x26, 0xbc, 0x39,
	0x2f, 0xff, 0xc9, 0x6f, 0xfc, 0x1f, 0x00, 0x00, 0xff, 0xff, 0xb3, 0x71, 0x4d, 0x42, 0x9e, 0x0c,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a Sequencer by address.
	Sequencer(ctx context.Context, in *QueryGetSequencerRequest, opts ...grpc.CallOption) (*QueryGetSequencerResponse, error)
	// Queries a list of Sequencer items.
	Sequencers(ctx context.Context, in *QuerySequencersRequest, opts ...grpc.CallOption) (*QuerySequencersResponse, error)
	// Queries a SequencersByRollapp by rollappId.
	SequencersByRollapp(ctx context.Context, in *QueryGetSequencersByRollappRequest, opts ...grpc.CallOption) (*QueryGetSequencersByRollappResponse, error)
	// Queries a SequencersByRollappByStatus
	SequencersByRollappByStatus(ctx context.Context, in *QueryGetSequencersByRollappByStatusRequest, opts ...grpc.CallOption) (*QueryGetSequencersByRollappByStatusResponse, error)
	UnConfirmSequencerAddressByRollappByStatus(ctx context.Context, in *QueryGetUnConfirmSequencersAddrByRollappRequest, opts ...grpc.CallOption) (*QueryGetUnConfirmSequencersAddrByRollappResponse, error)
	ReplaceProposerInfo(ctx context.Context, in *QueryReplaceProposerInfoRequest, opts ...grpc.CallOption) (*QueryReplaceProposerInfoResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/metaearth.sequencer.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Sequencer(ctx context.Context, in *QueryGetSequencerRequest, opts ...grpc.CallOption) (*QueryGetSequencerResponse, error) {
	out := new(QueryGetSequencerResponse)
	err := c.cc.Invoke(ctx, "/metaearth.sequencer.Query/Sequencer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Sequencers(ctx context.Context, in *QuerySequencersRequest, opts ...grpc.CallOption) (*QuerySequencersResponse, error) {
	out := new(QuerySequencersResponse)
	err := c.cc.Invoke(ctx, "/metaearth.sequencer.Query/Sequencers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) SequencersByRollapp(ctx context.Context, in *QueryGetSequencersByRollappRequest, opts ...grpc.CallOption) (*QueryGetSequencersByRollappResponse, error) {
	out := new(QueryGetSequencersByRollappResponse)
	err := c.cc.Invoke(ctx, "/metaearth.sequencer.Query/SequencersByRollapp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) SequencersByRollappByStatus(ctx context.Context, in *QueryGetSequencersByRollappByStatusRequest, opts ...grpc.CallOption) (*QueryGetSequencersByRollappByStatusResponse, error) {
	out := new(QueryGetSequencersByRollappByStatusResponse)
	err := c.cc.Invoke(ctx, "/metaearth.sequencer.Query/SequencersByRollappByStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) UnConfirmSequencerAddressByRollappByStatus(ctx context.Context, in *QueryGetUnConfirmSequencersAddrByRollappRequest, opts ...grpc.CallOption) (*QueryGetUnConfirmSequencersAddrByRollappResponse, error) {
	out := new(QueryGetUnConfirmSequencersAddrByRollappResponse)
	err := c.cc.Invoke(ctx, "/metaearth.sequencer.Query/UnConfirmSequencerAddressByRollappByStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ReplaceProposerInfo(ctx context.Context, in *QueryReplaceProposerInfoRequest, opts ...grpc.CallOption) (*QueryReplaceProposerInfoResponse, error) {
	out := new(QueryReplaceProposerInfoResponse)
	err := c.cc.Invoke(ctx, "/metaearth.sequencer.Query/ReplaceProposerInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a Sequencer by address.
	Sequencer(context.Context, *QueryGetSequencerRequest) (*QueryGetSequencerResponse, error)
	// Queries a list of Sequencer items.
	Sequencers(context.Context, *QuerySequencersRequest) (*QuerySequencersResponse, error)
	// Queries a SequencersByRollapp by rollappId.
	SequencersByRollapp(context.Context, *QueryGetSequencersByRollappRequest) (*QueryGetSequencersByRollappResponse, error)
	// Queries a SequencersByRollappByStatus
	SequencersByRollappByStatus(context.Context, *QueryGetSequencersByRollappByStatusRequest) (*QueryGetSequencersByRollappByStatusResponse, error)
	UnConfirmSequencerAddressByRollappByStatus(context.Context, *QueryGetUnConfirmSequencersAddrByRollappRequest) (*QueryGetUnConfirmSequencersAddrByRollappResponse, error)
	ReplaceProposerInfo(context.Context, *QueryReplaceProposerInfoRequest) (*QueryReplaceProposerInfoResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) Sequencer(ctx context.Context, req *QueryGetSequencerRequest) (*QueryGetSequencerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sequencer not implemented")
}
func (*UnimplementedQueryServer) Sequencers(ctx context.Context, req *QuerySequencersRequest) (*QuerySequencersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sequencers not implemented")
}
func (*UnimplementedQueryServer) SequencersByRollapp(ctx context.Context, req *QueryGetSequencersByRollappRequest) (*QueryGetSequencersByRollappResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SequencersByRollapp not implemented")
}
func (*UnimplementedQueryServer) SequencersByRollappByStatus(ctx context.Context, req *QueryGetSequencersByRollappByStatusRequest) (*QueryGetSequencersByRollappByStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SequencersByRollappByStatus not implemented")
}
func (*UnimplementedQueryServer) UnConfirmSequencerAddressByRollappByStatus(ctx context.Context, req *QueryGetUnConfirmSequencersAddrByRollappRequest) (*QueryGetUnConfirmSequencersAddrByRollappResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnConfirmSequencerAddressByRollappByStatus not implemented")
}
func (*UnimplementedQueryServer) ReplaceProposerInfo(ctx context.Context, req *QueryReplaceProposerInfoRequest) (*QueryReplaceProposerInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReplaceProposerInfo not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metaearth.sequencer.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Sequencer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetSequencerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Sequencer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metaearth.sequencer.Query/Sequencer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Sequencer(ctx, req.(*QueryGetSequencerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Sequencers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuerySequencersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Sequencers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metaearth.sequencer.Query/Sequencers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Sequencers(ctx, req.(*QuerySequencersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_SequencersByRollapp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetSequencersByRollappRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).SequencersByRollapp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metaearth.sequencer.Query/SequencersByRollapp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).SequencersByRollapp(ctx, req.(*QueryGetSequencersByRollappRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_SequencersByRollappByStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetSequencersByRollappByStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).SequencersByRollappByStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metaearth.sequencer.Query/SequencersByRollappByStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).SequencersByRollappByStatus(ctx, req.(*QueryGetSequencersByRollappByStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_UnConfirmSequencerAddressByRollappByStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetUnConfirmSequencersAddrByRollappRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).UnConfirmSequencerAddressByRollappByStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metaearth.sequencer.Query/UnConfirmSequencerAddressByRollappByStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).UnConfirmSequencerAddressByRollappByStatus(ctx, req.(*QueryGetUnConfirmSequencersAddrByRollappRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ReplaceProposerInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryReplaceProposerInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ReplaceProposerInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metaearth.sequencer.Query/ReplaceProposerInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ReplaceProposerInfo(ctx, req.(*QueryReplaceProposerInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "metaearth.sequencer.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "Sequencer",
			Handler:    _Query_Sequencer_Handler,
		},
		{
			MethodName: "Sequencers",
			Handler:    _Query_Sequencers_Handler,
		},
		{
			MethodName: "SequencersByRollapp",
			Handler:    _Query_SequencersByRollapp_Handler,
		},
		{
			MethodName: "SequencersByRollappByStatus",
			Handler:    _Query_SequencersByRollappByStatus_Handler,
		},
		{
			MethodName: "UnConfirmSequencerAddressByRollappByStatus",
			Handler:    _Query_UnConfirmSequencerAddressByRollappByStatus_Handler,
		},
		{
			MethodName: "ReplaceProposerInfo",
			Handler:    _Query_ReplaceProposerInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "metaearth/sequencer/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetSequencerRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetSequencerRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetSequencerRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.SequencerAddress) > 0 {
		i -= len(m.SequencerAddress)
		copy(dAtA[i:], m.SequencerAddress)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.SequencerAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetSequencerResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetSequencerResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetSequencerResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Sequencer.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QuerySequencersRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QuerySequencersRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QuerySequencersRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QuerySequencersResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QuerySequencersResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QuerySequencersResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Sequencers) > 0 {
		for iNdEx := len(m.Sequencers) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Sequencers[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetSequencersByRollappRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetSequencersByRollappRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetSequencersByRollappRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.RollappId) > 0 {
		i -= len(m.RollappId)
		copy(dAtA[i:], m.RollappId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.RollappId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetSequencersByRollappResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetSequencersByRollappResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetSequencersByRollappResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Sequencers) > 0 {
		for iNdEx := len(m.Sequencers) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Sequencers[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetSequencersByRollappByStatusRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetSequencersByRollappByStatusRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetSequencersByRollappByStatusRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Status != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x10
	}
	if len(m.RollappId) > 0 {
		i -= len(m.RollappId)
		copy(dAtA[i:], m.RollappId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.RollappId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetSequencersByRollappByStatusResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetSequencersByRollappByStatusResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetSequencersByRollappByStatusResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Sequencers) > 0 {
		for iNdEx := len(m.Sequencers) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Sequencers[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetUnConfirmSequencersAddrByRollappRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetUnConfirmSequencersAddrByRollappRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetUnConfirmSequencersAddrByRollappRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.BlockHeight != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.BlockHeight))
		i--
		dAtA[i] = 0x10
	}
	if len(m.RollappId) > 0 {
		i -= len(m.RollappId)
		copy(dAtA[i:], m.RollappId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.RollappId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetUnConfirmSequencersAddrByRollappResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetUnConfirmSequencersAddrByRollappResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetUnConfirmSequencersAddrByRollappResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.UnconfirmCacheHeight != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.UnconfirmCacheHeight))
		i--
		dAtA[i] = 0x18
	}
	if m.StartHeight != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.StartHeight))
		i--
		dAtA[i] = 0x10
	}
	{
		size, err := m.NewSequencer.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryReplaceProposerInfoRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryReplaceProposerInfoRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryReplaceProposerInfoRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.RollappId) > 0 {
		i -= len(m.RollappId)
		copy(dAtA[i:], m.RollappId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.RollappId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryReplaceProposerInfoResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryReplaceProposerInfoResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryReplaceProposerInfoResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.ReplaceProposer.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetSequencerRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.SequencerAddress)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetSequencerResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Sequencer.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QuerySequencersRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QuerySequencersResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Sequencers) > 0 {
		for _, e := range m.Sequencers {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetSequencersByRollappRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.RollappId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetSequencersByRollappResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Sequencers) > 0 {
		for _, e := range m.Sequencers {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *QueryGetSequencersByRollappByStatusRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.RollappId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.Status != 0 {
		n += 1 + sovQuery(uint64(m.Status))
	}
	return n
}

func (m *QueryGetSequencersByRollappByStatusResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Sequencers) > 0 {
		for _, e := range m.Sequencers {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *QueryGetUnConfirmSequencersAddrByRollappRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.RollappId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.BlockHeight != 0 {
		n += 1 + sovQuery(uint64(m.BlockHeight))
	}
	return n
}

func (m *QueryGetUnConfirmSequencersAddrByRollappResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.NewSequencer.Size()
	n += 1 + l + sovQuery(uint64(l))
	if m.StartHeight != 0 {
		n += 1 + sovQuery(uint64(m.StartHeight))
	}
	if m.UnconfirmCacheHeight != 0 {
		n += 1 + sovQuery(uint64(m.UnconfirmCacheHeight))
	}
	return n
}

func (m *QueryReplaceProposerInfoRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.RollappId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryReplaceProposerInfoResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ReplaceProposer.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetSequencerRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetSequencerRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetSequencerRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SequencerAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SequencerAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetSequencerResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetSequencerResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetSequencerResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sequencer", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Sequencer.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QuerySequencersRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QuerySequencersRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QuerySequencersRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QuerySequencersResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QuerySequencersResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QuerySequencersResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sequencers", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sequencers = append(m.Sequencers, Sequencer{})
			if err := m.Sequencers[len(m.Sequencers)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetSequencersByRollappRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetSequencersByRollappRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetSequencersByRollappRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RollappId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RollappId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetSequencersByRollappResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetSequencersByRollappResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetSequencersByRollappResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sequencers", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sequencers = append(m.Sequencers, Sequencer{})
			if err := m.Sequencers[len(m.Sequencers)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetSequencersByRollappByStatusRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetSequencersByRollappByStatusRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetSequencersByRollappByStatusRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RollappId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RollappId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= OperatingStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetSequencersByRollappByStatusResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetSequencersByRollappByStatusResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetSequencersByRollappByStatusResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sequencers", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sequencers = append(m.Sequencers, Sequencer{})
			if err := m.Sequencers[len(m.Sequencers)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetUnConfirmSequencersAddrByRollappRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetUnConfirmSequencersAddrByRollappRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetUnConfirmSequencersAddrByRollappRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RollappId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RollappId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockHeight", wireType)
			}
			m.BlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlockHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetUnConfirmSequencersAddrByRollappResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetUnConfirmSequencersAddrByRollappResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetUnConfirmSequencersAddrByRollappResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NewSequencer", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.NewSequencer.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartHeight", wireType)
			}
			m.StartHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StartHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UnconfirmCacheHeight", wireType)
			}
			m.UnconfirmCacheHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UnconfirmCacheHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryReplaceProposerInfoRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryReplaceProposerInfoRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryReplaceProposerInfoRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RollappId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RollappId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryReplaceProposerInfoResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryReplaceProposerInfoResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryReplaceProposerInfoResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReplaceProposer", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ReplaceProposer.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
