// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: metaearth/rollapp/genesis_bridge_data.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	types "github.com/cosmos/cosmos-sdk/x/bank/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	types1 "github.com/cosmos/ibc-go/v8/modules/apps/transfer/types"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisBridgeData is the data struct that is passed to the hub for the
// genesis bridge flow
type GenesisBridgeData struct {
	// genesis_info is the genesis info of the rollapp. used for hub validation
	GenesisInfo GenesisBridgeInfo `protobuf:"bytes,1,opt,name=genesis_info,json=genesisInfo,proto3" json:"genesis_info"`
	// native_denom is the native denom of the rollapp. registered on the hub
	NativeDenom types.Metadata `protobuf:"bytes,2,opt,name=native_denom,json=nativeDenom,proto3" json:"native_denom"`
	// optional genesis transfer packet data
	GenesisTransfer *types1.FungibleTokenPacketData `protobuf:"bytes,3,opt,name=genesis_transfer,json=genesisTransfer,proto3" json:"genesis_transfer,omitempty"`
}

func (m *GenesisBridgeData) Reset()         { *m = GenesisBridgeData{} }
func (m *GenesisBridgeData) String() string { return proto.CompactTextString(m) }
func (*GenesisBridgeData) ProtoMessage()    {}
func (*GenesisBridgeData) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0bd8c0a2bb372ea, []int{0}
}
func (m *GenesisBridgeData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisBridgeData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisBridgeData.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisBridgeData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisBridgeData.Merge(m, src)
}
func (m *GenesisBridgeData) XXX_Size() int {
	return m.Size()
}
func (m *GenesisBridgeData) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisBridgeData.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisBridgeData proto.InternalMessageInfo

func (m *GenesisBridgeData) GetGenesisInfo() GenesisBridgeInfo {
	if m != nil {
		return m.GenesisInfo
	}
	return GenesisBridgeInfo{}
}

func (m *GenesisBridgeData) GetNativeDenom() types.Metadata {
	if m != nil {
		return m.NativeDenom
	}
	return types.Metadata{}
}

func (m *GenesisBridgeData) GetGenesisTransfer() *types1.FungibleTokenPacketData {
	if m != nil {
		return m.GenesisTransfer
	}
	return nil
}

// The genesis info of the rollapp, that is passed to the hub for validation.
// it's populated on the InitGenesis of the rollapp
type GenesisBridgeInfo struct {
	// checksum used to verify integrity of the genesis file. currently unused
	GenesisChecksum string `protobuf:"bytes,1,opt,name=genesis_checksum,json=genesisChecksum,proto3" json:"genesis_checksum,omitempty"`
	// unique bech32 prefix
	Bech32Prefix string `protobuf:"bytes,2,opt,name=bech32_prefix,json=bech32Prefix,proto3" json:"bech32_prefix,omitempty"`
	// native_denom is the base denom for the native token
	NativeDenom DenomMetadata `protobuf:"bytes,3,opt,name=native_denom,json=nativeDenom,proto3" json:"native_denom"`
	// initial_supply is the initial supply of the native token
	InitialSupply cosmossdk_io_math.Int `protobuf:"bytes,4,opt,name=initial_supply,json=initialSupply,proto3,customtype=cosmossdk.io/math.Int" json:"initial_supply"`
	// accounts on the Hub to fund with some bootstrapping transfers
	GenesisAccounts []GenesisAccount `protobuf:"bytes,5,rep,name=genesis_accounts,json=genesisAccounts,proto3" json:"genesis_accounts"`
}

func (m *GenesisBridgeInfo) Reset()         { *m = GenesisBridgeInfo{} }
func (m *GenesisBridgeInfo) String() string { return proto.CompactTextString(m) }
func (*GenesisBridgeInfo) ProtoMessage()    {}
func (*GenesisBridgeInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0bd8c0a2bb372ea, []int{1}
}
func (m *GenesisBridgeInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisBridgeInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisBridgeInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisBridgeInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisBridgeInfo.Merge(m, src)
}
func (m *GenesisBridgeInfo) XXX_Size() int {
	return m.Size()
}
func (m *GenesisBridgeInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisBridgeInfo.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisBridgeInfo proto.InternalMessageInfo

func (m *GenesisBridgeInfo) GetGenesisChecksum() string {
	if m != nil {
		return m.GenesisChecksum
	}
	return ""
}

func (m *GenesisBridgeInfo) GetBech32Prefix() string {
	if m != nil {
		return m.Bech32Prefix
	}
	return ""
}

func (m *GenesisBridgeInfo) GetNativeDenom() DenomMetadata {
	if m != nil {
		return m.NativeDenom
	}
	return DenomMetadata{}
}

func (m *GenesisBridgeInfo) GetGenesisAccounts() []GenesisAccount {
	if m != nil {
		return m.GenesisAccounts
	}
	return nil
}

func init() {
	proto.RegisterType((*GenesisBridgeData)(nil), "metaearth.rollapp.GenesisBridgeData")
	proto.RegisterType((*GenesisBridgeInfo)(nil), "metaearth.rollapp.GenesisBridgeInfo")
}

func init() {
	proto.RegisterFile("metaearth/rollapp/genesis_bridge_data.proto", fileDescriptor_e0bd8c0a2bb372ea)
}

var fileDescriptor_e0bd8c0a2bb372ea = []byte{
	// 520 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0xc1, 0x4e, 0xdb, 0x30,
	0x1c, 0xc6, 0x5b, 0x60, 0x93, 0x08, 0x65, 0x1b, 0xd1, 0x26, 0x75, 0x48, 0x0b, 0x1d, 0xe3, 0x00,
	0x42, 0xd8, 0x22, 0x68, 0x0f, 0xb0, 0x0e, 0x31, 0xe5, 0x80, 0x84, 0x32, 0x4e, 0xbb, 0x64, 0xb6,
	0xeb, 0x26, 0x56, 0x12, 0xdb, 0x8a, 0x9d, 0x0a, 0xde, 0x61, 0x87, 0x3d, 0xcc, 0x1e, 0x82, 0x23,
	0xda, 0x61, 0x9a, 0x76, 0x40, 0x53, 0xfb, 0x22, 0x53, 0x6c, 0xa7, 0x65, 0x30, 0x76, 0x8b, 0xbf,
	0x7c, 0xff, 0xcf, 0xff, 0xef, 0x27, 0x7b, 0xfb, 0x25, 0xd5, 0x88, 0xa2, 0x4a, 0x67, 0xb0, 0x12,
	0x45, 0x81, 0xa4, 0x84, 0x29, 0xe5, 0x54, 0x31, 0x95, 0xe0, 0x8a, 0x8d, 0x52, 0x9a, 0x8c, 0x90,
	0x46, 0x40, 0x56, 0x42, 0x0b, 0x7f, 0x63, 0x6e, 0x06, 0xce, 0xbc, 0x19, 0x10, 0xa1, 0x4a, 0xa1,
	0x20, 0x46, 0x3c, 0x87, 0x93, 0x43, 0x4c, 0x35, 0x3a, 0x34, 0x07, 0x3b, 0xb2, 0xf9, 0xd2, 0xfe,
	0x4f, 0xcc, 0x09, 0xda, 0x83, 0xfb, 0xf5, 0x3c, 0x15, 0xa9, 0xb0, 0x7a, 0xf3, 0xe5, 0xd4, 0x3d,
	0x86, 0x09, 0x44, 0x52, 0x16, 0x8c, 0x20, 0xcd, 0x04, 0x57, 0x50, 0x57, 0x88, 0xab, 0x31, 0xad,
	0xe0, 0x24, 0x84, 0x12, 0x91, 0x9c, 0x6a, 0x67, 0xdd, 0x79, 0x78, 0x77, 0xc6, 0xc7, 0x6d, 0xe0,
	0xe0, 0xbe, 0xab, 0x51, 0x16, 0xb5, 0xb6, 0xbf, 0x2c, 0x79, 0x1b, 0x1f, 0xec, 0xe0, 0xd0, 0x74,
	0x3e, 0x46, 0x1a, 0xf9, 0xa7, 0x5e, 0xef, 0x76, 0x5a, 0xbf, 0x3b, 0xe8, 0xee, 0xae, 0x85, 0x3b,
	0xe0, 0x1e, 0x03, 0xf0, 0xd7, 0x6c, 0xc4, 0xc7, 0x62, 0xb8, 0x72, 0x75, 0xb3, 0xd5, 0x89, 0xd7,
	0xdc, 0x7c, 0x23, 0xf9, 0x27, 0x5e, 0x8f, 0x23, 0xcd, 0x26, 0x34, 0x19, 0x51, 0x2e, 0xca, 0xfe,
	0x92, 0x89, 0x7b, 0x05, 0x1c, 0x12, 0x83, 0xcc, 0xf1, 0x03, 0xa7, 0x6e, 0xbf, 0x36, 0xc7, 0x0e,
	0x1e, 0x37, 0x73, 0xfe, 0x67, 0xef, 0x59, 0xbb, 0x56, 0x0b, 0xa6, 0xbf, 0x6c, 0xb2, 0xde, 0x02,
	0x86, 0x09, 0xb8, 0x8d, 0x0e, 0xb4, 0x0e, 0x30, 0x09, 0xc1, 0x49, 0xcd, 0x53, 0x86, 0x0b, 0x7a,
	0x2e, 0x72, 0xca, 0xcf, 0x0c, 0xc7, 0xa6, 0x67, 0xfc, 0xd4, 0xc5, 0x9d, 0x3b, 0xef, 0xf6, 0x8f,
	0xbb, 0x38, 0xcc, 0xfe, 0x7b, 0x8b, 0x7b, 0x49, 0x46, 0x49, 0xae, 0xea, 0xd2, 0x20, 0x59, 0x9d,
	0x07, 0xbc, 0x77, 0xb2, 0xff, 0xc6, 0x5b, 0xc7, 0x94, 0x64, 0x47, 0x61, 0x22, 0x2b, 0x3a, 0x66,
	0x17, 0xa6, 0xeb, 0x6a, 0xdc, 0xb3, 0xe2, 0x99, 0xd1, 0xfc, 0xe8, 0x0e, 0x0f, 0xdb, 0x61, 0xf0,
	0x0f, 0xbc, 0xa6, 0xf7, 0xff, 0x90, 0xc4, 0xde, 0x13, 0xc6, 0x99, 0x66, 0xa8, 0x48, 0x54, 0x2d,
	0x65, 0x71, 0xd9, 0x5f, 0x69, 0x2e, 0x1c, 0xee, 0x37, 0xd6, 0x5f, 0x37, 0x5b, 0x2f, 0x2c, 0x63,
	0x35, 0xca, 0x01, 0x13, 0xb0, 0x44, 0x3a, 0x03, 0x11, 0xd7, 0xdf, 0xbf, 0x1d, 0x78, 0x0e, 0x7e,
	0xc4, 0x75, 0xbc, 0xee, 0x22, 0x3e, 0x9a, 0x04, 0x3f, 0x5e, 0xd4, 0x45, 0x84, 0x88, 0x9a, 0x6b,
	0xd5, 0x7f, 0x34, 0x58, 0xde, 0x5d, 0x0b, 0x5f, 0x3f, 0xfc, 0x02, 0xde, 0x59, 0xa7, 0xdb, 0xb1,
	0xe5, 0xe2, 0x54, 0x35, 0x8c, 0xae, 0xa6, 0x41, 0xf7, 0x7a, 0x1a, 0x74, 0x7f, 0x4f, 0x83, 0xee,
	0xd7, 0x59, 0xd0, 0xb9, 0x9e, 0x05, 0x9d, 0x9f, 0xb3, 0xa0, 0xf3, 0x09, 0xa6, 0x4c, 0x67, 0x35,
	0x06, 0x44, 0x94, 0x50, 0x48, 0xca, 0x17, 0x4f, 0xb6, 0xa4, 0x07, 0x59, 0x8d, 0xe1, 0xc5, 0xfc,
	0xed, 0xea, 0x4b, 0x49, 0x15, 0x7e, 0x6c, 0x5e, 0xee, 0xd1, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x14, 0x73, 0x2f, 0x2f, 0xbf, 0x03, 0x00, 0x00,
}

func (m *GenesisBridgeData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisBridgeData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisBridgeData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.GenesisTransfer != nil {
		{
			size, err := m.GenesisTransfer.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenesisBridgeData(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	{
		size, err := m.NativeDenom.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesisBridgeData(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size, err := m.GenesisInfo.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesisBridgeData(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *GenesisBridgeInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisBridgeInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisBridgeInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.GenesisAccounts) > 0 {
		for iNdEx := len(m.GenesisAccounts) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.GenesisAccounts[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesisBridgeData(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	{
		size := m.InitialSupply.Size()
		i -= size
		if _, err := m.InitialSupply.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGenesisBridgeData(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size, err := m.NativeDenom.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesisBridgeData(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.Bech32Prefix) > 0 {
		i -= len(m.Bech32Prefix)
		copy(dAtA[i:], m.Bech32Prefix)
		i = encodeVarintGenesisBridgeData(dAtA, i, uint64(len(m.Bech32Prefix)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.GenesisChecksum) > 0 {
		i -= len(m.GenesisChecksum)
		copy(dAtA[i:], m.GenesisChecksum)
		i = encodeVarintGenesisBridgeData(dAtA, i, uint64(len(m.GenesisChecksum)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintGenesisBridgeData(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesisBridgeData(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisBridgeData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.GenesisInfo.Size()
	n += 1 + l + sovGenesisBridgeData(uint64(l))
	l = m.NativeDenom.Size()
	n += 1 + l + sovGenesisBridgeData(uint64(l))
	if m.GenesisTransfer != nil {
		l = m.GenesisTransfer.Size()
		n += 1 + l + sovGenesisBridgeData(uint64(l))
	}
	return n
}

func (m *GenesisBridgeInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.GenesisChecksum)
	if l > 0 {
		n += 1 + l + sovGenesisBridgeData(uint64(l))
	}
	l = len(m.Bech32Prefix)
	if l > 0 {
		n += 1 + l + sovGenesisBridgeData(uint64(l))
	}
	l = m.NativeDenom.Size()
	n += 1 + l + sovGenesisBridgeData(uint64(l))
	l = m.InitialSupply.Size()
	n += 1 + l + sovGenesisBridgeData(uint64(l))
	if len(m.GenesisAccounts) > 0 {
		for _, e := range m.GenesisAccounts {
			l = e.Size()
			n += 1 + l + sovGenesisBridgeData(uint64(l))
		}
	}
	return n
}

func sovGenesisBridgeData(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesisBridgeData(x uint64) (n int) {
	return sovGenesisBridgeData(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisBridgeData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesisBridgeData
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisBridgeData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisBridgeData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GenesisInfo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesisBridgeData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesisBridgeData
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesisBridgeData
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.GenesisInfo.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NativeDenom", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesisBridgeData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesisBridgeData
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesisBridgeData
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.NativeDenom.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GenesisTransfer", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesisBridgeData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesisBridgeData
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesisBridgeData
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.GenesisTransfer == nil {
				m.GenesisTransfer = &types1.FungibleTokenPacketData{}
			}
			if err := m.GenesisTransfer.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesisBridgeData(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesisBridgeData
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GenesisBridgeInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesisBridgeData
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisBridgeInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisBridgeInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GenesisChecksum", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesisBridgeData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesisBridgeData
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesisBridgeData
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GenesisChecksum = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Bech32Prefix", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesisBridgeData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesisBridgeData
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesisBridgeData
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Bech32Prefix = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NativeDenom", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesisBridgeData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesisBridgeData
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesisBridgeData
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.NativeDenom.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InitialSupply", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesisBridgeData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesisBridgeData
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesisBridgeData
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.InitialSupply.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GenesisAccounts", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesisBridgeData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesisBridgeData
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesisBridgeData
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GenesisAccounts = append(m.GenesisAccounts, GenesisAccount{})
			if err := m.GenesisAccounts[len(m.GenesisAccounts)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesisBridgeData(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesisBridgeData
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesisBridgeData(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesisBridgeData
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesisBridgeData
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesisBridgeData
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesisBridgeData
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesisBridgeData
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesisBridgeData
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesisBridgeData        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesisBridgeData          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesisBridgeData = fmt.Errorf("proto: unexpected end of group")
)
