// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: metaearth/rollapp/rollapp.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Rollapp_VMType int32

const (
	Rollapp_Unspecified Rollapp_VMType = 0
	Rollapp_EVM         Rollapp_VMType = 1
	Rollapp_WASM        Rollapp_VMType = 2
)

var Rollapp_VMType_name = map[int32]string{
	0: "Unspecified",
	1: "EVM",
	2: "WASM",
}

var Rollapp_VMType_value = map[string]int32{
	"Unspecified": 0,
	"EVM":         1,
	"WASM":        2,
}

func (x Rollapp_VMType) String() string {
	return proto.EnumName(Rollapp_VMType_name, int32(x))
}

func (Rollapp_VMType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d4f36334349c5ab1, []int{1, 0}
}

// RollappGenesisState is a partial repr of the state the hub can expect the
// rollapp to be in upon genesis
type RollappGenesisState struct {
	// 0 means unpopulated
	// If populated, it's the proof height that the hub received the genesis
	// transfer packet from the rollapp. If populated, the bridge is considered
	// open. It's not allowed to fork to a height prior to this height.
	TransferProofHeight uint64 `protobuf:"varint,3,opt,name=transfer_proof_height,json=transferProofHeight,proto3" json:"transfer_proof_height,omitempty"`
}

func (m *RollappGenesisState) Reset()         { *m = RollappGenesisState{} }
func (m *RollappGenesisState) String() string { return proto.CompactTextString(m) }
func (*RollappGenesisState) ProtoMessage()    {}
func (*RollappGenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4f36334349c5ab1, []int{0}
}
func (m *RollappGenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RollappGenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RollappGenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RollappGenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RollappGenesisState.Merge(m, src)
}
func (m *RollappGenesisState) XXX_Size() int {
	return m.Size()
}
func (m *RollappGenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_RollappGenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_RollappGenesisState proto.InternalMessageInfo

func (m *RollappGenesisState) GetTransferProofHeight() uint64 {
	if m != nil {
		return m.TransferProofHeight
	}
	return 0
}

// Rollapp defines a rollapp object. First, the RollApp is created and then
// sequencers can be created and attached. The RollApp is identified by
// rollappId
type Rollapp struct {
	// The unique identifier of the rollapp chain.
	// The rollapp_id follows the same standard as cosmos chain_id.
	RollappId string `protobuf:"bytes,1,opt,name=rollapp_id,json=rollappId,proto3" json:"rollapp_id,omitempty"`
	// owner is the bech32-encoded address of the rollapp owner.
	Owner string `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	// genesis_state is a partial repr of the state the hub can expect the rollapp
	// to be in upon genesis
	GenesisState RollappGenesisState `protobuf:"bytes,7,opt,name=genesis_state,json=genesisState,proto3" json:"genesis_state"`
	// channel_id will be set to the canonical IBC channel of the rollapp.
	ChannelId string `protobuf:"bytes,8,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	// metadata is the rollapp metadata
	Metadata *RollappMetadata `protobuf:"bytes,11,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// genesis_info keeps immutable rollapp fields
	GenesisInfo GenesisInfo `protobuf:"bytes,12,opt,name=genesis_info,json=genesisInfo,proto3" json:"genesis_info"`
	// initial_sequencer is an option to preset one or more coma-separated
	// bech32-encoded addresses of the sequencer(s) that are allowed to initially
	// register and serve for this rollapp. if left empty, no sequencer is allowed
	// to register. if set to "*" any sequencer can register.
	InitialSequencer string `protobuf:"bytes,13,opt,name=initial_sequencer,json=initialSequencer,proto3" json:"initial_sequencer,omitempty"`
	// How much a sequencer needs to have at stake to be proposer.
	// Denom is dym. It is empty or ONE coin only. Coins is just a convenience to
	// avoid marshalling issues.
	MinSequencerBond github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,20,rep,name=min_sequencer_bond,json=minSequencerBond,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"min_sequencer_bond" yaml:"min_sequencer_bond"`
	// vm_type is the type of rollapp machine: EVM or WASM
	VmType Rollapp_VMType `protobuf:"varint,14,opt,name=vm_type,json=vmType,proto3,enum=metaearth.rollapp.Rollapp_VMType" json:"vm_type,omitempty"`
	// launched is a boolean that indicates that the Rollapp has been launched and
	// the immutable fields are no longer updatable.
	Launched bool `protobuf:"varint,15,opt,name=launched,proto3" json:"launched,omitempty"`
	// pre_launch_time is the timestamp indicating the time before which the
	// rollapp cannot be started.
	// Set when creating IRO plan for the rollapp
	PreLaunchTime *time.Time `protobuf:"bytes,16,opt,name=pre_launch_time,json=preLaunchTime,proto3,stdtime" json:"pre_launch_time,omitempty"`
	// LivenessEventHeight is the height on the HUB of an upcoming liveness event
	// (slash or jail against the rollapp). 0 means not set
	LivenessEventHeight int64 `protobuf:"varint,17,opt,name=liveness_event_height,json=livenessEventHeight,proto3" json:"liveness_event_height,omitempty"`
	// The height on the HUB that we start counting liveness from. If the rollapp
	// is not active for a long time after this height, a liveness event will
	// happen.
	LivenessCountdownStartHeight int64 `protobuf:"varint,18,opt,name=liveness_countdown_start_height,json=livenessCountdownStartHeight,proto3" json:"liveness_countdown_start_height,omitempty"`
	// Revisions is a list of all the rollapp revisions.
	Revisions []Revision `protobuf:"bytes,19,rep,name=revisions,proto3" json:"revisions"`
	// togglable by owner: enable fast finalization via TEE nodes (note: global
	// gov param required too)
	EnableTee bool `protobuf:"varint,21,opt,name=enable_tee,json=enableTee,proto3" json:"enable_tee,omitempty"`
}

func (m *Rollapp) Reset()         { *m = Rollapp{} }
func (m *Rollapp) String() string { return proto.CompactTextString(m) }
func (*Rollapp) ProtoMessage()    {}
func (*Rollapp) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4f36334349c5ab1, []int{1}
}
func (m *Rollapp) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Rollapp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Rollapp.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Rollapp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rollapp.Merge(m, src)
}
func (m *Rollapp) XXX_Size() int {
	return m.Size()
}
func (m *Rollapp) XXX_DiscardUnknown() {
	xxx_messageInfo_Rollapp.DiscardUnknown(m)
}

var xxx_messageInfo_Rollapp proto.InternalMessageInfo

func (m *Rollapp) GetRollappId() string {
	if m != nil {
		return m.RollappId
	}
	return ""
}

func (m *Rollapp) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *Rollapp) GetGenesisState() RollappGenesisState {
	if m != nil {
		return m.GenesisState
	}
	return RollappGenesisState{}
}

func (m *Rollapp) GetChannelId() string {
	if m != nil {
		return m.ChannelId
	}
	return ""
}

func (m *Rollapp) GetMetadata() *RollappMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *Rollapp) GetGenesisInfo() GenesisInfo {
	if m != nil {
		return m.GenesisInfo
	}
	return GenesisInfo{}
}

func (m *Rollapp) GetInitialSequencer() string {
	if m != nil {
		return m.InitialSequencer
	}
	return ""
}

func (m *Rollapp) GetMinSequencerBond() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.MinSequencerBond
	}
	return nil
}

func (m *Rollapp) GetVmType() Rollapp_VMType {
	if m != nil {
		return m.VmType
	}
	return Rollapp_Unspecified
}

func (m *Rollapp) GetLaunched() bool {
	if m != nil {
		return m.Launched
	}
	return false
}

func (m *Rollapp) GetPreLaunchTime() *time.Time {
	if m != nil {
		return m.PreLaunchTime
	}
	return nil
}

func (m *Rollapp) GetLivenessEventHeight() int64 {
	if m != nil {
		return m.LivenessEventHeight
	}
	return 0
}

func (m *Rollapp) GetLivenessCountdownStartHeight() int64 {
	if m != nil {
		return m.LivenessCountdownStartHeight
	}
	return 0
}

func (m *Rollapp) GetRevisions() []Revision {
	if m != nil {
		return m.Revisions
	}
	return nil
}

func (m *Rollapp) GetEnableTee() bool {
	if m != nil {
		return m.EnableTee
	}
	return false
}

// Revision is a representation of the rollapp revision.
type Revision struct {
	// Number is the revision number of the rollapp. Always start with 0 revision.
	Number uint64 `protobuf:"varint,19,opt,name=number,proto3" json:"number,omitempty"`
	// StartHeight is the first height of the rollapp when the revision started.
	StartHeight uint64 `protobuf:"varint,20,opt,name=start_height,json=startHeight,proto3" json:"start_height,omitempty"`
}

func (m *Revision) Reset()         { *m = Revision{} }
func (m *Revision) String() string { return proto.CompactTextString(m) }
func (*Revision) ProtoMessage()    {}
func (*Revision) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4f36334349c5ab1, []int{2}
}
func (m *Revision) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Revision) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Revision.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Revision) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Revision.Merge(m, src)
}
func (m *Revision) XXX_Size() int {
	return m.Size()
}
func (m *Revision) XXX_DiscardUnknown() {
	xxx_messageInfo_Revision.DiscardUnknown(m)
}

var xxx_messageInfo_Revision proto.InternalMessageInfo

func (m *Revision) GetNumber() uint64 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *Revision) GetStartHeight() uint64 {
	if m != nil {
		return m.StartHeight
	}
	return 0
}

// Rollapp summary is a compact representation of Rollapp
type RollappSummary struct {
	// The unique identifier of the rollapp chain.
	// The rollappId follows the same standard as cosmos chain_id.
	RollappId string `protobuf:"bytes,1,opt,name=rollappId,proto3" json:"rollappId,omitempty"`
	// Defines the index of the last rollapp UpdateState.
	LatestStateIndex *StateInfoIndex `protobuf:"bytes,2,opt,name=latestStateIndex,proto3" json:"latestStateIndex,omitempty"`
	// Defines the index of the last rollapp UpdateState that was finalized.
	LatestFinalizedStateIndex *StateInfoIndex `protobuf:"bytes,3,opt,name=latestFinalizedStateIndex,proto3" json:"latestFinalizedStateIndex,omitempty"`
	LatestHeight              uint64          `protobuf:"varint,4,opt,name=latestHeight,proto3" json:"latestHeight,omitempty"`
	LatestFinalizedHeight     uint64          `protobuf:"varint,5,opt,name=latestFinalizedHeight,proto3" json:"latestFinalizedHeight,omitempty"`
}

func (m *RollappSummary) Reset()         { *m = RollappSummary{} }
func (m *RollappSummary) String() string { return proto.CompactTextString(m) }
func (*RollappSummary) ProtoMessage()    {}
func (*RollappSummary) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4f36334349c5ab1, []int{3}
}
func (m *RollappSummary) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RollappSummary) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RollappSummary.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RollappSummary) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RollappSummary.Merge(m, src)
}
func (m *RollappSummary) XXX_Size() int {
	return m.Size()
}
func (m *RollappSummary) XXX_DiscardUnknown() {
	xxx_messageInfo_RollappSummary.DiscardUnknown(m)
}

var xxx_messageInfo_RollappSummary proto.InternalMessageInfo

func (m *RollappSummary) GetRollappId() string {
	if m != nil {
		return m.RollappId
	}
	return ""
}

func (m *RollappSummary) GetLatestStateIndex() *StateInfoIndex {
	if m != nil {
		return m.LatestStateIndex
	}
	return nil
}

func (m *RollappSummary) GetLatestFinalizedStateIndex() *StateInfoIndex {
	if m != nil {
		return m.LatestFinalizedStateIndex
	}
	return nil
}

func (m *RollappSummary) GetLatestHeight() uint64 {
	if m != nil {
		return m.LatestHeight
	}
	return 0
}

func (m *RollappSummary) GetLatestFinalizedHeight() uint64 {
	if m != nil {
		return m.LatestFinalizedHeight
	}
	return 0
}

func init() {
	proto.RegisterEnum("metaearth.rollapp.Rollapp_VMType", Rollapp_VMType_name, Rollapp_VMType_value)
	proto.RegisterType((*RollappGenesisState)(nil), "metaearth.rollapp.RollappGenesisState")
	proto.RegisterType((*Rollapp)(nil), "metaearth.rollapp.Rollapp")
	proto.RegisterType((*Revision)(nil), "metaearth.rollapp.Revision")
	proto.RegisterType((*RollappSummary)(nil), "metaearth.rollapp.RollappSummary")
}

func init() { proto.RegisterFile("metaearth/rollapp/rollapp.proto", fileDescriptor_d4f36334349c5ab1) }

var fileDescriptor_d4f36334349c5ab1 = []byte{
	// 886 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0x4d, 0x6e, 0xdb, 0x46,
	0x14, 0x16, 0x2d, 0xc5, 0xa2, 0x46, 0x8a, 0x4d, 0x8f, 0xec, 0x82, 0x56, 0x13, 0x49, 0x21, 0x8a,
	0x42, 0x40, 0x1b, 0x12, 0x71, 0xbb, 0xca, 0xa2, 0x45, 0x15, 0xb8, 0x89, 0x8c, 0x0a, 0x68, 0x29,
	0x27, 0x05, 0xba, 0x21, 0x46, 0xe2, 0x93, 0x34, 0x28, 0x39, 0xc3, 0x72, 0x46, 0x4a, 0xdc, 0x53,
	0x64, 0xd5, 0x43, 0xf4, 0x04, 0x5d, 0xf4, 0x00, 0x59, 0x66, 0xd9, 0x55, 0x52, 0xd8, 0x37, 0xe8,
	0x09, 0x0a, 0x0e, 0x87, 0x92, 0x52, 0xc9, 0x40, 0x57, 0xe4, 0xbc, 0xef, 0x7b, 0xdf, 0xfb, 0x99,
	0xf7, 0x06, 0x75, 0x62, 0x90, 0x04, 0x48, 0x2a, 0xe7, 0x5e, 0xca, 0xa3, 0x88, 0x24, 0x49, 0xf1,
	0x75, 0x93, 0x94, 0x4b, 0x8e, 0x8f, 0x56, 0x04, 0x57, 0x03, 0xad, 0xf6, 0x84, 0x8b, 0x98, 0x0b,
	0x6f, 0x4c, 0x04, 0x78, 0xcb, 0x47, 0x63, 0x90, 0xe4, 0x91, 0x37, 0xe1, 0x94, 0xe5, 0x2e, 0xad,
	0xe3, 0x19, 0x9f, 0x71, 0xf5, 0xeb, 0x65, 0x7f, 0xda, 0xda, 0x99, 0x71, 0x3e, 0x8b, 0xc0, 0x53,
	0xa7, 0xf1, 0x62, 0xea, 0x49, 0x1a, 0x83, 0x90, 0x24, 0xd6, 0x91, 0x5a, 0x9f, 0x6c, 0xa7, 0x32,
	0x03, 0x06, 0x82, 0x8a, 0x80, 0xb2, 0x69, 0x21, 0xd3, 0xdd, 0x66, 0x65, 0x96, 0x90, 0x48, 0xa2,
	0x19, 0xce, 0x36, 0x43, 0x48, 0x22, 0x61, 0x43, 0xc5, 0x79, 0x8e, 0x9a, 0x7e, 0x8e, 0x3d, 0xcd,
	0x43, 0x8c, 0x32, 0x06, 0x3e, 0x43, 0x27, 0x32, 0x25, 0x4c, 0x4c, 0x21, 0x0d, 0x92, 0x94, 0xf3,
	0x69, 0x30, 0x07, 0x3a, 0x9b, 0x4b, 0xbb, 0xdc, 0x35, 0x7a, 0x15, 0xbf, 0x59, 0x80, 0xdf, 0x67,
	0xd8, 0x33, 0x05, 0x5d, 0x54, 0x4c, 0xc3, 0xda, 0xbb, 0xa8, 0x98, 0x7b, 0x56, 0xd9, 0xf9, 0xb3,
	0x8a, 0xaa, 0x5a, 0x17, 0xdf, 0x47, 0x48, 0x87, 0x0f, 0x68, 0x68, 0x1b, 0x5d, 0xa3, 0x57, 0xf3,
	0x6b, 0xda, 0x32, 0x08, 0xf1, 0x31, 0xba, 0xc3, 0x5f, 0x32, 0x48, 0xed, 0x3d, 0x85, 0xe4, 0x07,
	0xfc, 0x03, 0xba, 0x5b, 0xd4, 0xac, 0x72, 0xb6, 0xab, 0x5d, 0xa3, 0x57, 0x3f, 0xfb, 0xd4, 0xdd,
	0xba, 0x05, 0x77, 0x47, 0xfe, 0xfd, 0xca, 0x9b, 0x77, 0x9d, 0x92, 0xdf, 0x98, 0x6d, 0xd6, 0x74,
	0x1f, 0xa1, 0xc9, 0x9c, 0x30, 0x06, 0x51, 0x96, 0x87, 0x99, 0xe7, 0xa1, 0x2d, 0x83, 0x10, 0x7f,
	0x85, 0xcc, 0xa2, 0x7f, 0x76, 0x5d, 0x05, 0x73, 0x6e, 0x0f, 0x36, 0xd4, 0x4c, 0x7f, 0xe5, 0x83,
	0x9f, 0xa2, 0xc6, 0xe6, 0x2d, 0xd9, 0x0d, 0xa5, 0xd1, 0xde, 0xa1, 0xa1, 0x33, 0x1d, 0xb0, 0x29,
	0xd7, 0x89, 0xd6, 0x67, 0x6b, 0x13, 0xfe, 0x0c, 0x1d, 0x51, 0x46, 0x25, 0x25, 0x51, 0x20, 0xe0,
	0x97, 0x05, 0xb0, 0x09, 0xa4, 0xf6, 0x5d, 0x95, 0xae, 0xa5, 0x81, 0x51, 0x61, 0xc7, 0xbf, 0x19,
	0x08, 0xc7, 0x94, 0xad, 0x99, 0xc1, 0x98, 0xb3, 0xd0, 0x3e, 0xee, 0x96, 0x7b, 0xf5, 0xb3, 0x53,
	0x37, 0x1f, 0x50, 0x37, 0x1b, 0x50, 0x57, 0x0f, 0xa8, 0xfb, 0x84, 0x53, 0xd6, 0x1f, 0x66, 0x71,
	0xff, 0x79, 0xd7, 0x39, 0xbd, 0x22, 0x71, 0xf4, 0xd8, 0xd9, 0x96, 0x70, 0x7e, 0x7f, 0xdf, 0xe9,
	0xcd, 0xa8, 0x9c, 0x2f, 0xc6, 0xee, 0x84, 0xc7, 0x9e, 0x1e, 0xf5, 0xfc, 0xf3, 0x50, 0x84, 0x3f,
	0x7b, 0xf2, 0x2a, 0x01, 0xa1, 0xd4, 0x84, 0x6f, 0xc5, 0x94, 0xad, 0x92, 0xea, 0x73, 0x16, 0xe2,
	0xc7, 0xa8, 0xba, 0x8c, 0x83, 0x8c, 0x63, 0x1f, 0x74, 0x8d, 0xde, 0xc1, 0xd9, 0x83, 0xdb, 0xbb,
	0xe9, 0xbe, 0x18, 0x5e, 0x5e, 0x25, 0xe0, 0xef, 0x2f, 0xe3, 0xec, 0x8b, 0x5b, 0xc8, 0x8c, 0xc8,
	0x82, 0x4d, 0xe6, 0x10, 0xda, 0x87, 0x5d, 0xa3, 0x67, 0xfa, 0xab, 0x33, 0x7e, 0x86, 0x0e, 0x93,
	0x14, 0x82, 0xfc, 0x1c, 0x64, 0xab, 0x63, 0x5b, 0xaa, 0xd3, 0x2d, 0x37, 0xdf, 0x2b, 0xb7, 0xd8,
	0x2b, 0xf7, 0xb2, 0xd8, 0xab, 0x7e, 0xe5, 0xf5, 0xfb, 0x8e, 0xe1, 0xdf, 0x4d, 0x52, 0xf8, 0x4e,
	0xf9, 0x65, 0x48, 0x36, 0xe3, 0x11, 0x5d, 0x66, 0x8d, 0x17, 0x01, 0x2c, 0x81, 0xc9, 0x62, 0xc6,
	0x8f, 0xba, 0x46, 0xaf, 0xec, 0x37, 0x0b, 0xf0, 0x3c, 0xc3, 0xf2, 0x19, 0xc7, 0xe7, 0xa8, 0xb3,
	0xf2, 0x99, 0xf0, 0x05, 0x93, 0x21, 0x7f, 0xc9, 0xb2, 0x09, 0x4d, 0x57, 0xde, 0x58, 0x79, 0xdf,
	0x2b, 0x68, 0x4f, 0x0a, 0xd6, 0x28, 0x23, 0x69, 0x99, 0xaf, 0x51, 0x2d, 0x85, 0x25, 0x15, 0x94,
	0x33, 0x61, 0x37, 0xd5, 0x5d, 0x7d, 0xbc, 0xab, 0x3d, 0x9a, 0xa3, 0xa7, 0x64, 0xed, 0x93, 0xcd,
	0x32, 0x30, 0x32, 0x8e, 0x20, 0x90, 0x00, 0xf6, 0x89, 0xea, 0x51, 0x2d, 0xb7, 0x5c, 0x02, 0x38,
	0x9f, 0xa3, 0xfd, 0xbc, 0xa5, 0xf8, 0x10, 0xd5, 0x9f, 0x33, 0x91, 0xc0, 0x84, 0x4e, 0x29, 0x84,
	0x56, 0x09, 0x57, 0x51, 0xf9, 0xfc, 0xc5, 0xd0, 0x32, 0xb0, 0x89, 0x2a, 0x3f, 0x7e, 0x33, 0x1a,
	0xaa, 0x95, 0x2d, 0x5b, 0xd5, 0x8b, 0x8a, 0x59, 0xb3, 0xd0, 0x45, 0xc5, 0x44, 0x56, 0xdd, 0x39,
	0x47, 0x66, 0x11, 0x1b, 0x7f, 0x84, 0xf6, 0xd9, 0x22, 0x1e, 0x43, 0x6a, 0x37, 0xd5, 0xee, 0xeb,
	0x13, 0x7e, 0x80, 0x1a, 0x1f, 0xd4, 0x7d, 0xac, 0xd0, 0xba, 0x58, 0x97, 0xe9, 0xfc, 0xb1, 0x87,
	0x0e, 0xf4, 0x15, 0x8f, 0x16, 0x71, 0x4c, 0xd2, 0x2b, 0x7c, 0x0f, 0xad, 0x57, 0x7f, 0xfb, 0x2d,
	0x18, 0x22, 0x2b, 0x22, 0x12, 0x84, 0x54, 0x1b, 0x3b, 0x60, 0x21, 0xbc, 0x52, 0xcf, 0x42, 0x7d,
	0xe7, 0xf4, 0x68, 0xd2, 0x94, 0x2b, 0xa2, 0xbf, 0xe5, 0x8a, 0x03, 0x74, 0x9a, 0xdb, 0xbe, 0xa5,
	0x8c, 0x44, 0xf4, 0x57, 0x08, 0x37, 0x74, 0xcb, 0xff, 0x57, 0xf7, 0x76, 0x0d, 0xec, 0xa0, 0x46,
	0x0e, 0xe6, 0x05, 0xdb, 0x15, 0xd5, 0x83, 0x0f, 0x6c, 0xf8, 0x4b, 0x74, 0xf2, 0x1f, 0x01, 0x4d,
	0xbe, 0xa3, 0xc8, 0xbb, 0xc1, 0xfe, 0xe0, 0xcd, 0x75, 0xdb, 0x78, 0x7b, 0xdd, 0x36, 0xfe, 0xbe,
	0x6e, 0x1b, 0xaf, 0x6f, 0xda, 0xa5, 0xb7, 0x37, 0xed, 0xd2, 0x5f, 0x37, 0xed, 0xd2, 0x4f, 0xde,
	0xc6, 0x52, 0xf2, 0x04, 0xd8, 0xfa, 0x91, 0x8f, 0xe1, 0xe1, 0x7c, 0x31, 0xf6, 0x5e, 0xad, 0x5e,
	0x7b, 0xb5, 0xa1, 0xe3, 0x7d, 0xb5, 0x10, 0x5f, 0xfc, 0x1b, 0x00, 0x00, 0xff, 0xff, 0xd6, 0x81,
	0x69, 0xbf, 0xe2, 0x06, 0x00, 0x00,
}

func (m *RollappGenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RollappGenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RollappGenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.TransferProofHeight != 0 {
		i = encodeVarintRollapp(dAtA, i, uint64(m.TransferProofHeight))
		i--
		dAtA[i] = 0x18
	}
	return len(dAtA) - i, nil
}

func (m *Rollapp) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Rollapp) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Rollapp) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.EnableTee {
		i--
		if m.EnableTee {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xa8
	}
	if len(m.MinSequencerBond) > 0 {
		for iNdEx := len(m.MinSequencerBond) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.MinSequencerBond[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintRollapp(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1
			i--
			dAtA[i] = 0xa2
		}
	}
	if len(m.Revisions) > 0 {
		for iNdEx := len(m.Revisions) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Revisions[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintRollapp(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1
			i--
			dAtA[i] = 0x9a
		}
	}
	if m.LivenessCountdownStartHeight != 0 {
		i = encodeVarintRollapp(dAtA, i, uint64(m.LivenessCountdownStartHeight))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x90
	}
	if m.LivenessEventHeight != 0 {
		i = encodeVarintRollapp(dAtA, i, uint64(m.LivenessEventHeight))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x88
	}
	if m.PreLaunchTime != nil {
		n1, err1 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(*m.PreLaunchTime, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.PreLaunchTime):])
		if err1 != nil {
			return 0, err1
		}
		i -= n1
		i = encodeVarintRollapp(dAtA, i, uint64(n1))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x82
	}
	if m.Launched {
		i--
		if m.Launched {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x78
	}
	if m.VmType != 0 {
		i = encodeVarintRollapp(dAtA, i, uint64(m.VmType))
		i--
		dAtA[i] = 0x70
	}
	if len(m.InitialSequencer) > 0 {
		i -= len(m.InitialSequencer)
		copy(dAtA[i:], m.InitialSequencer)
		i = encodeVarintRollapp(dAtA, i, uint64(len(m.InitialSequencer)))
		i--
		dAtA[i] = 0x6a
	}
	{
		size, err := m.GenesisInfo.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintRollapp(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x62
	if m.Metadata != nil {
		{
			size, err := m.Metadata.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintRollapp(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x5a
	}
	if len(m.ChannelId) > 0 {
		i -= len(m.ChannelId)
		copy(dAtA[i:], m.ChannelId)
		i = encodeVarintRollapp(dAtA, i, uint64(len(m.ChannelId)))
		i--
		dAtA[i] = 0x42
	}
	{
		size, err := m.GenesisState.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintRollapp(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x3a
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintRollapp(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.RollappId) > 0 {
		i -= len(m.RollappId)
		copy(dAtA[i:], m.RollappId)
		i = encodeVarintRollapp(dAtA, i, uint64(len(m.RollappId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Revision) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Revision) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Revision) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.StartHeight != 0 {
		i = encodeVarintRollapp(dAtA, i, uint64(m.StartHeight))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xa0
	}
	if m.Number != 0 {
		i = encodeVarintRollapp(dAtA, i, uint64(m.Number))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x98
	}
	return len(dAtA) - i, nil
}

func (m *RollappSummary) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RollappSummary) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RollappSummary) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.LatestFinalizedHeight != 0 {
		i = encodeVarintRollapp(dAtA, i, uint64(m.LatestFinalizedHeight))
		i--
		dAtA[i] = 0x28
	}
	if m.LatestHeight != 0 {
		i = encodeVarintRollapp(dAtA, i, uint64(m.LatestHeight))
		i--
		dAtA[i] = 0x20
	}
	if m.LatestFinalizedStateIndex != nil {
		{
			size, err := m.LatestFinalizedStateIndex.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintRollapp(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.LatestStateIndex != nil {
		{
			size, err := m.LatestStateIndex.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintRollapp(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.RollappId) > 0 {
		i -= len(m.RollappId)
		copy(dAtA[i:], m.RollappId)
		i = encodeVarintRollapp(dAtA, i, uint64(len(m.RollappId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintRollapp(dAtA []byte, offset int, v uint64) int {
	offset -= sovRollapp(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *RollappGenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.TransferProofHeight != 0 {
		n += 1 + sovRollapp(uint64(m.TransferProofHeight))
	}
	return n
}

func (m *Rollapp) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.RollappId)
	if l > 0 {
		n += 1 + l + sovRollapp(uint64(l))
	}
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovRollapp(uint64(l))
	}
	l = m.GenesisState.Size()
	n += 1 + l + sovRollapp(uint64(l))
	l = len(m.ChannelId)
	if l > 0 {
		n += 1 + l + sovRollapp(uint64(l))
	}
	if m.Metadata != nil {
		l = m.Metadata.Size()
		n += 1 + l + sovRollapp(uint64(l))
	}
	l = m.GenesisInfo.Size()
	n += 1 + l + sovRollapp(uint64(l))
	l = len(m.InitialSequencer)
	if l > 0 {
		n += 1 + l + sovRollapp(uint64(l))
	}
	if m.VmType != 0 {
		n += 1 + sovRollapp(uint64(m.VmType))
	}
	if m.Launched {
		n += 2
	}
	if m.PreLaunchTime != nil {
		l = github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.PreLaunchTime)
		n += 2 + l + sovRollapp(uint64(l))
	}
	if m.LivenessEventHeight != 0 {
		n += 2 + sovRollapp(uint64(m.LivenessEventHeight))
	}
	if m.LivenessCountdownStartHeight != 0 {
		n += 2 + sovRollapp(uint64(m.LivenessCountdownStartHeight))
	}
	if len(m.Revisions) > 0 {
		for _, e := range m.Revisions {
			l = e.Size()
			n += 2 + l + sovRollapp(uint64(l))
		}
	}
	if len(m.MinSequencerBond) > 0 {
		for _, e := range m.MinSequencerBond {
			l = e.Size()
			n += 2 + l + sovRollapp(uint64(l))
		}
	}
	if m.EnableTee {
		n += 3
	}
	return n
}

func (m *Revision) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Number != 0 {
		n += 2 + sovRollapp(uint64(m.Number))
	}
	if m.StartHeight != 0 {
		n += 2 + sovRollapp(uint64(m.StartHeight))
	}
	return n
}

func (m *RollappSummary) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.RollappId)
	if l > 0 {
		n += 1 + l + sovRollapp(uint64(l))
	}
	if m.LatestStateIndex != nil {
		l = m.LatestStateIndex.Size()
		n += 1 + l + sovRollapp(uint64(l))
	}
	if m.LatestFinalizedStateIndex != nil {
		l = m.LatestFinalizedStateIndex.Size()
		n += 1 + l + sovRollapp(uint64(l))
	}
	if m.LatestHeight != 0 {
		n += 1 + sovRollapp(uint64(m.LatestHeight))
	}
	if m.LatestFinalizedHeight != 0 {
		n += 1 + sovRollapp(uint64(m.LatestFinalizedHeight))
	}
	return n
}

func sovRollapp(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozRollapp(x uint64) (n int) {
	return sovRollapp(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *RollappGenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRollapp
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RollappGenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RollappGenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TransferProofHeight", wireType)
			}
			m.TransferProofHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRollapp
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TransferProofHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipRollapp(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRollapp
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Rollapp) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRollapp
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Rollapp: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Rollapp: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RollappId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRollapp
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRollapp
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRollapp
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RollappId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRollapp
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRollapp
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRollapp
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GenesisState", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRollapp
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRollapp
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRollapp
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.GenesisState.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChannelId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRollapp
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRollapp
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRollapp
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChannelId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Metadata", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRollapp
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRollapp
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRollapp
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Metadata == nil {
				m.Metadata = &RollappMetadata{}
			}
			if err := m.Metadata.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GenesisInfo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRollapp
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRollapp
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRollapp
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.GenesisInfo.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InitialSequencer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRollapp
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRollapp
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRollapp
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.InitialSequencer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 14:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VmType", wireType)
			}
			m.VmType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRollapp
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.VmType |= Rollapp_VMType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 15:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Launched", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRollapp
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Launched = bool(v != 0)
		case 16:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PreLaunchTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRollapp
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRollapp
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRollapp
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.PreLaunchTime == nil {
				m.PreLaunchTime = new(time.Time)
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(m.PreLaunchTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 17:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LivenessEventHeight", wireType)
			}
			m.LivenessEventHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRollapp
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LivenessEventHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 18:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LivenessCountdownStartHeight", wireType)
			}
			m.LivenessCountdownStartHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRollapp
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LivenessCountdownStartHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 19:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Revisions", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRollapp
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRollapp
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRollapp
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Revisions = append(m.Revisions, Revision{})
			if err := m.Revisions[len(m.Revisions)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 20:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinSequencerBond", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRollapp
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRollapp
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRollapp
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MinSequencerBond = append(m.MinSequencerBond, types.Coin{})
			if err := m.MinSequencerBond[len(m.MinSequencerBond)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 21:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EnableTee", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRollapp
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.EnableTee = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipRollapp(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRollapp
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Revision) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRollapp
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Revision: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Revision: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 19:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Number", wireType)
			}
			m.Number = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRollapp
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Number |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 20:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartHeight", wireType)
			}
			m.StartHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRollapp
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StartHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipRollapp(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRollapp
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RollappSummary) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRollapp
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RollappSummary: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RollappSummary: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RollappId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRollapp
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRollapp
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRollapp
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RollappId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LatestStateIndex", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRollapp
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRollapp
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRollapp
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.LatestStateIndex == nil {
				m.LatestStateIndex = &StateInfoIndex{}
			}
			if err := m.LatestStateIndex.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LatestFinalizedStateIndex", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRollapp
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRollapp
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRollapp
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.LatestFinalizedStateIndex == nil {
				m.LatestFinalizedStateIndex = &StateInfoIndex{}
			}
			if err := m.LatestFinalizedStateIndex.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LatestHeight", wireType)
			}
			m.LatestHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRollapp
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LatestHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LatestFinalizedHeight", wireType)
			}
			m.LatestFinalizedHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRollapp
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LatestFinalizedHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipRollapp(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRollapp
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipRollapp(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowRollapp
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowRollapp
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowRollapp
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthRollapp
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupRollapp
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthRollapp
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthRollapp        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowRollapp          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupRollapp = fmt.Errorf("proto: unexpected end of group")
)
