name: Build and Release Rollapp

on:
  push:
    tags:
      - 'v*'  # This workflow triggers on version tags, e.g., v1.0.0
    branches-ignore:
      - '*' 
  pull_request:
    branches: [ "releases" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: recursive
        persist-credentials: false  # Important: disable default credentials
        token: ${{ secrets.GO_MOD_FETCH }}  # Use the personal access token for both repo and submodules

    # Set up Go environment
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.0'

    # Authenticate with GitHub to access private repositories
    - name: Set up authentication for private repos
      run: |
        git config --global url."https://github.com:${{ secrets.GO_MOD_FETCH }}@github.com".insteadOf "https://github.com"
        go env -w GOPRIVATE=github.com/st-chain
        go get github.com/st-chain/me-rdk

    # Install dependencies
    - name: Install dependencies
      run: go mod tidy

    # Build the project using Make
    - name: Build the project
      run: make build

    # Archive the build output
    - name: Archive the build output
      run: tar -czvf med.tar.gz -C build med

    # Upload the build as an artifact (optional, for debugging or other workflows)
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: med
        path: med.tar.gz
        
  release:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')

    steps:
    # Checkout the code again for the release
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download build artifact
      uses: actions/download-artifact@v4
      with:
        name: med
    # Determine if the release should be marked as pre-release based on the tag name
    - name: Set pre-release flag
      id: prerelease_check
      run: |
        if [[ "${GITHUB_REF##*/}" =~ rc ]]; then
          echo "prerelease=true" >> $GITHUB_ENV
        else
          echo "prerelease=false" >> $GITHUB_ENV
        fi
    # Create release branch based on the tag
    - name: Create release branch
      run: |
        TAG_NAME="${GITHUB_REF##*/}"
        BRANCH_NAME="release/${TAG_NAME}"
        git checkout -b "${BRANCH_NAME}"
        git push origin "${BRANCH_NAME}"

    # Generate release body description
    - name: Generate release body
      id: release_body
      run: |
        echo "Release for tag ${{ github.ref_name }}" > release_body.txt
        
      #echo "Changes in this release:" >> release_body.txt
      #echo "- Add your changelog or commit details here." >> release_body.txt

    # Create a release and upload the build output
    - name: Upload release asset
      uses: softprops/action-gh-release@v1
      with:
        files: med.tar.gz
        body_path: release_body.txt
        prerelease: ${{ env.prerelease }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
