name: Build and deploy b2-197 env

on:
  push:
    branches:
      - 'test1230'

jobs:
  build:
    runs-on: b2-local

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: recursive
        persist-credentials: false  # Important: disable default credentials
        token: ${{ secrets.GO_MOD_FETCH }}  # Use the personal access token for both repo and submodules

    # Authenticate with GitHub to access private repositories
    - name: Set up authentication for private repos
      run: |
        git config --global url."https://github.com:${{ secrets.GO_MOD_FETCH }}@github.com".insteadOf "https://github.com"
        go env -w GOPRIVATE=github.com/st-chain

    # Install dependencies
    - name: Install dependencies
      run: |
        go mod tidy

    # Build the project using Make
    - name: Build the project
      run: make build

    # deploy
    - name: deploy st 197
      run: |
        ssh user1@192.168.0.197 'pkill med || true'
        scp ./build/med user1@192.168.0.197:/home/user1/bin/
        ssh user1@192.168.0.197 '/home/user1/bin/me.sh start_all'
